import {expect,test,type Page,devices} from "@playwright/test";
import {mkdir} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
const evidence=process.env.WYBP_COWRIE_COMMERCE_EVIDENCE||join(tmpdir(),"wybp-cowrie-commerce-evidence");
const reference=`cw_${"a".repeat(32)}`;const order=`rr_${"b".repeat(32)}`;
const products=[{productKey:"cowrie_5_v1",quantity:5,displayPrice:"£1.99"},{productKey:"cowrie_15_v1",quantity:15,displayPrice:"£4.99"},{productKey:"cowrie_40_v1",quantity:40,displayPrice:"£9.99"}];
async function capture(page:Page,name:string){await page.screenshot({path:join(evidence,`${name}.png`),fullPage:true});}
async function fixtures(page:Page){
 await page.route("**/*",route=>{const url=new URL(route.request().url());return ["127.0.0.1","localhost"].includes(url.hostname)?route.continue():route.abort();});
 await page.route("**/cowries/projection",route=>route.fulfill({json:{available:true,wallet:{walletReference:reference,state:"active",totalBalance:5,purchasedBalance:3,bonusBalance:2,freeQuickPlaysRemaining:2,bonusExpiresAfterDays:180}}}));
 await page.route("**/commerce/status",route=>route.fulfill({json:{available:true,bundles:products}}));
}
async function open(page:Page){await fixtures(page);await page.goto("/");await page.getByRole("button",{name:/Cowries 5/}).click();await expect(page.getByRole("heading",{name:"One-off Cowrie bundles"})).toBeVisible();}
test.beforeAll(()=>mkdir(evidence,{recursive:true}));
test("bundle selection is deliberate, consent unchecked/separate, exact prices; protected same-window checkout stores only reference",async({page})=>{
 await open(page);await capture(page,"bundle-selector");const consent=page.getByRole("checkbox",{name:/Draft immediate digital-delivery notice/});await expect(consent).not.toBeChecked();await expect(page.locator('input[name="cowrie-bundle"]:checked')).toHaveCount(0);await capture(page,"consent-unchecked");await page.getByRole("button",{name:"Continue to Stripe",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"Choose a bundle"})).toBeVisible();await capture(page,"consent-validation");
 for(const product of products){await page.getByRole("radio",{name:`${product.quantity} Cowries, ${product.displayPrice}`}).check();await expect(consent).not.toBeChecked();await expect(page.getByRole("button",{name:`Continue to Stripe · ${product.displayPrice}`})).toBeVisible();await capture(page,`${product.quantity}-cowrie-purchase`);}
 await page.getByRole("radio",{name:"5 Cowries, £1.99"}).check();await consent.check();let posted:Record<string,unknown>|null=null;let navigation:string|null=null;
 await page.route("**/commerce/orders",async route=>{posted=route.request().postDataJSON();await route.fulfill({status:201,json:{publicOrderReference:order,productKey:"cowrie_5_v1",quantity:5,displayPrice:"£1.99",state:"pending",pendingExpiresAt:Date.now()+1800000,paymentLinkUrl:`https://buy.stripe.com/test_review_cowrie_5_v1?client_reference_id=${order}`}});});
 await page.route("https://buy.stripe.com/**",route=>{navigation=route.request().url();return route.abort();});await page.getByRole("button",{name:"Continue to Stripe · £1.99"}).click();await expect.poll(()=>navigation).toContain(`client_reference_id=${order}`);expect(Object.keys(posted!).sort()).toEqual(["anonymousSessionCredential","consentNoticeVersion","idempotencyKey","immediateDeliveryConsent","productKey","walletReference"]);expect(posted!.immediateDeliveryConsent).toBe(true);expect(navigation).not.toContain(reference);
});
test("protected return removes query values, uses server status and preserves refund/dispute distinction",async({page})=>{
 await fixtures(page);let resolveRequest:()=>void=()=>{};const release=new Promise<void>(resolve=>{resolveRequest=resolve;});let targetState="processing";let cause:string|undefined;let polls=0;
 await page.route("**/commerce/status",async route=>{const body=route.request().postDataJSON();expect(Object.keys(body).sort()).toEqual(["anonymousSessionCredential","publicOrderReference"]);expect(body.publicOrderReference).toBe(order);polls++;if(polls===1)await release;await route.fulfill({json:{state:targetState,entitlementActive:false,productKey:"cowrie_5_v1",quantity:5,wallet:{purchasedBalance:5,bonusBalance:2,totalBalance:7},...(cause?{settlementCause:cause}:{})}});});
 await page.addInitScript(reference=>{sessionStorage.setItem("wybp-cowrie-pending-order-v1",reference);const time=Date.now();sessionStorage.setItem("wybp-anonymous-session-v1",JSON.stringify({version:1,id:"a".repeat(32),createdAt:time,expiresAt:time+86400000}));},order);
 await page.goto("/cowries/return?paid=1&quantity=999&balance=999&session_id=cs_untrusted&product=cowrie_40_v1");await expect(page.getByRole("heading",{name:"Confirming your payment"})).toBeVisible();await capture(page,"confirming-payment");expect(page.url()).not.toContain("?");resolveRequest();await expect(page.getByRole("heading",{name:"Your payment is still processing"})).toBeVisible();await capture(page,"payment-processing");
 for(const [state,title,name,settlement] of [["fulfilled","Your Cowries are ready","purchase-successful",undefined],["failed","Payment could not be completed","payment-failed",undefined],["refunded","This purchase was refunded","refunded-allocation","refund"],["disputed","This purchase is disputed","disputed-allocation","dispute"],["review_required","This purchase needs protected owner review","review-required-allocation","dispute"]]){targetState=state!;cause=settlement;await page.goto("/cowries/return?paid=1&balance=999");await expect(page.getByRole("heading",{name:title})).toBeVisible();await expect(page.getByText("Current available wallet balance:")).toContainText("7 Cowries");await capture(page,name!);if(state==="fulfilled")await capture(page,"updated-wallet-balance");if(state==="review_required")await expect(page.getByText(/not an ordinary customer refund/)).toBeVisible();}
 expect(polls).toBeGreaterThanOrEqual(6);
});
test("unavailable bank hides offers, 320/Android/iPhone/zoom/focus/reduced-motion layouts stay usable",async({browser,page})=>{
 await open(page);await page.setViewportSize({width:320,height:720});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await capture(page,"layout-320");await page.setViewportSize({width:1280,height:960});await page.evaluate(()=>{document.documentElement.style.zoom="2";});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await capture(page,"zoom-200");await page.evaluate(()=>{document.documentElement.style.zoom="1";});await page.getByRole("radio",{name:"5 Cowries, £1.99"}).focus();await expect(page.locator(":focus")).toBeVisible();await capture(page,"keyboard-focus");await page.emulateMedia({reducedMotion:"reduce"});await capture(page,"reduced-motion");await page.getByRole("button",{name:"Close Cowrie Wallet"}).click();await expect(page.getByRole("button",{name:/Cowries 5/})).toBeFocused();
 for(const [name,device] of [["android",devices["Pixel 7"]],["iphone",devices["iPhone 13"]]] as const){const context=await browser.newContext({...device});const mobile=await context.newPage();await open(mobile);expect(await mobile.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await capture(mobile,`${name}-layout`);await context.close();}
 await page.route("**/commerce/status",route=>route.fulfill({status:503,json:{accepted:false}}));await page.reload();await page.getByRole("button",{name:/Cowries 5/}).click();await expect(page.getByRole("heading",{name:"One-off Cowrie bundles"})).toHaveCount(0);
});
