import { expect,test,type Page } from "@playwright/test";
import { mkdir,readFile } from "node:fs/promises";
import { join } from "node:path";
const evidence=process.env.WYBP_COMMERCE_VISUAL_DIR||join(process.cwd(),"test-results","prompt17");
const url=(scenario:string)=>`/?commerce_fixture=${scenario}`;
async function shot(page:Page,name:string){await mkdir(evidence,{recursive:true});await page.screenshot({path:join(evidence,`${name}.png`),fullPage:true});}
function pngDimensions(bytes:Buffer){expect(bytes.subarray(1,4).toString()).toBe("PNG");return{width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)};}

test("offer is post-result, honest, unchecked and leaves every free action reachable",async({page})=>{const external:string[]=[];page.on("request",request=>{if(!request.url().startsWith("http://127.0.0.1"))external.push(request.url());});await page.goto(url("offer"));const offer=page.locator(".royal-offer");await expect(offer).toContainText("Make your reveal unforgettable");await expect(offer).toContainText("£1.99");await expect(offer).toContainText("One-off payment");await expect(offer).toContainText("No subscription");await expect(offer).toContainText("A playful culture score, never a measure of human worth.");await expect(offer.locator("input[type=checkbox]")).not.toBeChecked();await expect(page.locator("#free-result-actions")).toBeVisible();await shot(page,"free-result-royal-reveal-offer");await offer.getByRole("button",{name:"Unlock for £1.99"}).click();await expect(offer.getByRole("alert")).toContainText("Please confirm");await shot(page,"immediate-delivery-consent-validation");expect(external).toEqual([]);});

test("processing, failure and refund fixtures remain neutral and preserve the free result",async({page})=>{for(const [scenario,name] of [["processing","payment-processing"],["failed","payment-failed"],["refunded","refunded-entitlement"]] as const){await page.goto(url(scenario));await expect(page.locator(".royal-offer")).toBeVisible();await expect(page.locator("#free-result-actions")).toBeVisible();await shot(page,name);}});

test("active pack exposes three portraits, certificate, premium video and correct downloaded PNGs",async({page})=>{await page.goto(url("succeeded"));await expect(page.locator(".royal-pack")).toContainText("Payment verified");await shot(page,"payment-succeeded");await page.goto(url("active"));const pack=page.locator(".royal-pack");await expect(pack).toContainText("Your Royal Reveal Pack");await expect(pack.locator(".royal-portrait-card")).toHaveCount(3);await expect(pack).toContainText("Royal Gold");await expect(pack).toContainText("Cowrie Crown");await expect(pack).toContainText("Indigo Celebration");await shot(page,"premium-portrait-selector");await mkdir(evidence,{recursive:true});const portraitNames=["royal-gold","cowrie-crown","indigo-celebration"];const cards=await pack.locator(".royal-portrait-card").all();for(let index=0;index<cards.length;index+=1){const card=cards[index];await card.screenshot({path:join(evidence,`${portraitNames[index]}-portrait.png`)});const download=page.waitForEvent("download");await card.getByRole("button",{name:"Download"}).click();const item=await download;const path=await item.path();expect(path).toBeTruthy();expect(pngDimensions(await readFile(path!))).toEqual({width:1080,height:1350});expect(item.suggestedFilename()).toMatch(/portrait\.png$/);}const certificateDownload=page.waitForEvent("download");await pack.getByRole("button",{name:"Download certificate"}).click();const certificate=await certificateDownload;expect(pngDimensions(await readFile((await certificate.path())!))).toEqual({width:2480,height:3508});expect(certificate.suggestedFilename()).toMatch(/certificate\.png$/);await shot(page,"certificate-preview");await expect(pack.locator(".story-video-panel")).toContainText("Create Story video");await shot(page,"video-ready-premium-panel");});

test("unsupported video keeps the free static fallback",async({page})=>{await page.goto(url("unsupported_video"));const panel=page.locator(".story-video-panel");await expect(panel).toContainText("Use static Story image instead");await panel.getByRole("button",{name:"Generate five-second video"}).click();await expect(panel).toContainText("cannot record a Story video");await shot(page,"unsupported-video-fallback");});

test("320px, Android, iPhone, zoom, keyboard and reduced motion remain accessible",async({page})=>{for(const [width,height,name] of [[320,700,"layout-320"],[360,800,"layout-android"],[390,844,"layout-iphone"]] as const){await page.setViewportSize({width,height});await page.goto(url("offer"));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);const controls=await page.locator(".royal-offer :is(button,a,input)").evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().height));expect(controls.every(height=>height>=20)).toBe(true);await shot(page,name);}await page.setViewportSize({width:640,height:760});await page.goto(url("offer"));await page.evaluate(()=>{document.documentElement.style.zoom="2";});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await shot(page,"layout-200-percent-zoom");await page.keyboard.press("Tab");await page.keyboard.press("Tab");await shot(page,"keyboard-focus");await page.emulateMedia({reducedMotion:"reduce"});await page.goto(url("active"));await expect(page.locator(".story-video-panel")).toHaveAttribute("data-reduced-motion","true");await shot(page,"reduced-motion");});
