"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {readAnonymousSession} from "../../anonymousSession.ts";
import {COWRIE_PENDING_ORDER_KEY,COWRIE_RETURN_POLL_INTERVAL_MS,COWRIE_RETURN_POLL_LIMIT,readPendingCowrieOrder,readCowriePurchaseStatus} from "../../cowrieCommerceClient.ts";
const messages:Readonly<Record<string,string>>={confirming:"Confirming your payment",pending:"Confirming your payment",paid:"Confirming your payment",processing:"Your payment is still processing",fulfilled:"Your Cowries are ready",failed:"Payment could not be completed",refunded:"This purchase was refunded",disputed:"This purchase is disputed",review_required:"This purchase needs protected owner review",expired:"This pending order has expired",deleted:"This purchase is unavailable",unavailable:"Payment status is unavailable",timeout:"Payment confirmation is taking longer than expected"};
export default function CowrieReturnClient(){const [state,setState]=useState("confirming");const [balance,setBalance]=useState<number|null>(null);const [cause,setCause]=useState<string|undefined>();const [quantity,setQuantity]=useState<number|null>(null);
 useEffect(()=>{
  window.history.replaceState(null,"",window.location.pathname);
  const controller=new AbortController();let stopped=false;const budget=setTimeout(()=>{if(!stopped){controller.abort();setState("timeout");}},18000);let timer:ReturnType<typeof setTimeout>|undefined;
  const reference=readPendingCowrieOrder(window.sessionStorage);const owner=readAnonymousSession(window.sessionStorage);
  const poll=async(count:number)=>{try{if(!reference||!owner.available)throw new Error("unavailable");const result=await readCowriePurchaseStatus(reference,owner.sessionId,controller.signal);if(stopped)return;setState(result.state);setCause(result.settlementCause);setBalance(result.totalBalance);setQuantity(result.quantity);if(["pending","processing","paid"].includes(result.state)){if(count>=COWRIE_RETURN_POLL_LIMIT){setState("timeout");return;}timer=setTimeout(()=>void poll(count+1),COWRIE_RETURN_POLL_INTERVAL_MS);}else{clearTimeout(budget);window.sessionStorage.removeItem(COWRIE_PENDING_ORDER_KEY);}}catch{if(!stopped&&!controller.signal.aborted){clearTimeout(budget);setState("unavailable");}}};
  void poll(1);return()=>{stopped=true;clearTimeout(budget);controller.abort();if(timer)clearTimeout(timer);};
 },[]);
 return <main className="cowrie-return"><p>Protected payment status</p><h1 aria-live="polite">{messages[state]||messages.unavailable}</h1>{state==="fulfilled"&&<p>{quantity} purchased Cowries were credited only after verified payment.</p>}{balance!==null&&<p>Current available wallet balance: <strong>{balance} Cowries</strong></p>}{["pending","paid","processing","timeout"].includes(state)&&<p>Do not purchase again while confirmation is pending. Keep your existing recovery credential safe and use the protected wallet or support process.</p>}{state==="review_required"&&<p>{cause==="dispute"?"This disputed purchase has already-used or unreconciled Cowries and needs owner review. It is not an ordinary customer refund.":"Partial refunds or already-used Cowries need owner review."} No debt or proportional refund removal is created automatically.</p>}{state==="disputed"&&<p>Only unused Cowries from this purchase are removed. Other purchases and bonus Cowries are preserved.</p>}<p>This page cannot credit a balance or confirm payment from a redirect.</p><Link href="/">Return to wallet and free game options</Link><p>Daily Challenges and incoming challenges stay free.</p><p className="cowrie-worth">A playful culture score, never a measure of human worth.</p></main>;
}
