"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { anonymousSessionStorageKey } from "../../anonymousSession.ts";
import { emitAnalyticsLocalEvent } from "../../analyticsLocal.ts";
import RoyalRevealPack from "../../RoyalRevealPack.tsx";

const pendingOrderKey="wybp-royal-reveal-pending-v1";
function credential():string|null{try{const raw=sessionStorage.getItem(anonymousSessionStorageKey);if(!raw||raw.length>256)return null;const value=JSON.parse(raw) as Record<string,unknown>;return value.version===1&&typeof value.id==="string"&&/^[0-9a-f]{32}$/.test(value.id)&&Number(value.expiresAt)>Date.now()?value.id:null;}catch{return null;}}
export default function RoyalRevealReturnClient(){const [state,setState]=useState<"confirming"|"success"|"failed"|"incomplete">("confirming");const [entitlement,setEntitlement]=useState<unknown>(null);
 useEffect(()=>{history.replaceState(history.state,"",location.pathname);const raw=sessionStorage.getItem(pendingOrderKey);const ownerCredential=credential();let reference:string|null=null;try{const value=raw?JSON.parse(raw) as Record<string,unknown>:null;reference=value&&value.version===1&&typeof value.publicOrderReference==="string"&&/^rr_[0-9a-f]{32}$/.test(value.publicOrderReference)?value.publicOrderReference:null;}catch{reference=null;}let cancelled=false;if(!reference||!ownerCredential){window.setTimeout(()=>{if(!cancelled)setState("incomplete");},0);return()=>{cancelled=true;};}let attempts=0;const poll=async()=>{attempts+=1;try{const response=await fetch("/commerce/status",{method:"POST",mode:"same-origin",credentials:"omit",referrerPolicy:"no-referrer",headers:{"content-type":"application/json"},body:JSON.stringify({publicOrderReference:reference,anonymousSessionCredential:ownerCredential})});const result=await response.json() as Record<string,unknown>;if(cancelled)return;if(result.entitlementActive===true&&result.entitlement){setEntitlement(result.entitlement);setState("success");sessionStorage.removeItem(pendingOrderKey);emitAnalyticsLocalEvent({name:"checkout_complete",properties:{surface:"result",outcome:"success"}});emitAnalyticsLocalEvent({name:"purchase_complete",properties:{surface:"result",outcome:"success"}});return;}if(result.state==="failed"){setState("failed");emitAnalyticsLocalEvent({name:"payment_failed",properties:{surface:"result",outcome:"failed"}});return;}if(result.state==="refunded"||result.state==="disputed"){setState("failed");emitAnalyticsLocalEvent({name:"refund_complete",properties:{surface:"result",outcome:"success"}});return;}}catch{/* bounded retry below */}if(attempts<12&&!cancelled)window.setTimeout(()=>void poll(),1500);else if(!cancelled)setState("incomplete");};void poll();return()=>{cancelled=true;};},[]);
 if(state==="success")return <RoyalRevealPack entitlement={entitlement}/>;return <section className="royal-return" aria-labelledby="royal-return-title" role="status" aria-live="polite"><span className={state==="confirming"?"royal-spinner":""} aria-hidden="true"/><h1 id="royal-return-title">{state==="confirming"?"Confirming your payment":state==="failed"?"Payment not completed":"We’re still waiting for confirmation"}</h1><p>{state==="confirming"?"Access is granted only after a verified Stripe webhook confirms the exact £1.99 payment.":"Your free result remains available. You can return safely and retry later."}</p><Link href="/">Return to the free result</Link></section>;
}
