import type { Metadata } from "next";
import { LegalPage, draftRobots } from "../legalPage.tsx";
import { createPublicAppUrl } from "../publicAppOrigin.ts";

export const metadata:Metadata={title:"Draft Privacy Notice | What’s Your Bride Price?",description:"Technical draft explaining privacy and data handling for What’s Your Bride Price?.",alternates:{canonical:createPublicAppUrl("/privacy")},robots:draftRobots};
export default function PrivacyPage(){return <LegalPage kicker="UK privacy information" title="Privacy Notice">
  <p>This technical draft covers the quiz website, its optional sharing, challenge, analytics, public-result and Royal Reveal capabilities. The controller’s legal identity and approved contact details are not configured, so production activation must fail closed.</p>
  <h2>Information and purpose</h2><ul><li>On-device quiz state, optional display name and optional private photograph support play and local media generation.</li><li>When durable features are activated, anonymous ownership credentials are transformed server-side for completed results, public-result controls and challenges. Raw credentials are not stored as bearer substitutes.</li><li>Explicitly published results expose only an authoritative score, edition, approved avatar, derived title and the neutral name “A challenger”.</li><li>Challenge links may expose the reviewed inviter name, approved avatar, edition and verified score while active.</li><li>Optional first-party analytics records only allowlisted events after affirmative consent. It excludes names, photographs, answers, raw codes, credentials, advertising identifiers, cross-site tracking and individual profiling.</li><li>Royal Reveal records controlled order, entitlement and verified Stripe lifecycle data. Payment-card details remain with Stripe.</li></ul>
  <h2>On-device and server-held data</h2><p>Quiz recovery, best scores, consent choice and tab credentials use browser storage described in the <a href="/privacy/storage">Cookie and Local Storage Notice</a>. Private photographs stay in browser memory by default and are never uploaded. Server records exist only for separately feature-gated capabilities and require approved storage bindings before production use.</p>
  <h2>Purposes and lawful bases</h2><p>Required functionality is limited to features the user requests. Optional analytics relies on affirmative consent in the implemented control. Final UK GDPR lawful bases for all server processing, consumer fulfilment, fraud prevention, legal obligations and any legitimate-interest assessment require owner and professional approval; none is invented here.</p>
  <h2>Sharing, recipients and transfers</h2><p>OpenAI Sites or trusted dispatch may process requests as platform provider. Stripe acts under its own payment privacy information after deliberate navigation. Social platforms receive data only after a deliberate navigation or browser share handoff. Processor terms, roles and any international-transfer mechanisms require separate review before activation.</p>
  <h2>Retention and security</h2><p>See the <a href="/privacy/retention">retention schedule</a>. Completed and published results expire exactly 90 days after authoritative quiz completion; publication does not extend that period. Access controls use opaque public references, bounded inputs, server-authoritative expiry and ownership proof without exposing internal hashes or credentials. This notice intentionally omits exploitable operational detail.</p>
  <h2>Your UK data-protection rights</h2><p>Depending on the circumstances, rights may include access, rectification, erasure, restriction, portability, objection and withdrawal of consent. Withdrawal of analytics consent takes effect immediately for future collection. The right to complain to the UK Information Commissioner’s Office remains available. Read <a href="/privacy/requests">how to make a privacy request</a>.</p>
  <h2>Automated decisions, profiling and children</h2><p>The playful score applies transparent quiz scoring; it does not make legal or similarly significant decisions and is not individual profiling for advertising. The service is intended primarily for adults and people above the applicable age of digital consent and is not directed at children under 13 in the UK. It does not collect dates of birth or infer age. The final numeric minimum-audience and Children’s Code decisions require owner and professional approval.</p>
  <h2>Future statistical-purpose exception</h2><p>The stricter opt-in analytics model remains. Any future reliance on a UK statistical-purpose exception would require separate owner and professional review of purpose limitation, individual-level retention, aggregation, objection controls and UK GDPR lawful basis.</p>
  <h2>Contact and review</h2><p>No privacy email, postal address, data protection officer, company number or ICO registration number is configured. Do not send personal information until an approved contact route is published.</p>
 </LegalPage>}
