export type RegionId = "west" | "east" | "central" | "north" | "southern";

export type QuizOption = { label: string; points: number };
export type QuizQuestion = { category: string; question: string; options: QuizOption[]; fact: string };
export type Region = {
  id: RegionId;
  name: string;
  shortName: string;
  invitation: string;
  flavour: string;
  art: string;
};

export const regions: Region[] = [
  { id: "west", name: "West Africa", shortName: "West", invitation: "Rhythm, cloth, cuisine and living memory", flavour: "From griot traditions and indigo cloth to highlife, fonio and family celebration.", art: "/regions/west-africa.webp" },
  { id: "east", name: "East Africa", shortName: "East", invitation: "Coast, highlands, language and ceremony", flavour: "From Swahili sayings and barkcloth to teff, Moutya and Oromo governance.", art: "/regions/east-africa.webp" },
  { id: "central", name: "Central Africa", shortName: "Central", invitation: "Forest, raffia, sound and style", flavour: "From Kuba cloth and soukous to makossa, mvet epics and cassava-leaf dishes.", art: "/regions/central-africa.webp" },
  { id: "north", name: "North Africa", shortName: "North", invitation: "Mosaic, desert, medina and melody", flavour: "From zellige and Amazigh heritage to couscous, raï, Gnawa and desert traditions.", art: "/regions/north-africa.webp" },
  { id: "southern", name: "Southern Africa", shortName: "Southern", invitation: "Stone, philosophy, beadwork and beat", flavour: "From Ubuntu and Great Zimbabwe to mbira, gumboot rhythm and mural colour.", art: "/regions/southern-africa.webp" },
];

export const questionsByRegion: Record<RegionId, QuizQuestion[]> = {
  west: [
    { category: "Music", question: "A traditional kora most commonly has how many strings?", options: [{ label: "21", points: 10 }, { label: "6", points: 1 }, { label: "12", points: 3 }, { label: "48", points: 0 }], fact: "The kora is a 21-string bridge-harp associated especially with Manding musical traditions." },
    { category: "Storytelling", question: "What is a griot best known for?", options: [{ label: "Preserving history through genealogy, praise, story and music", points: 10 }, { label: "Building river canoes", points: 1 }, { label: "Weaving only royal cloth", points: 2 }, { label: "Leading desert caravans", points: 0 }], fact: "Griots are oral historians, genealogists, musicians and keepers of memory in several West African societies." },
    { category: "Cloth", question: "Kente cloth is especially associated with which traditions?", options: [{ label: "Akan and Ewe traditions in Ghana", points: 10 }, { label: "Tuareg traditions in Niger", points: 2 }, { label: "Zulu traditions in South Africa", points: 0 }, { label: "Somali traditions in the Horn", points: 0 }], fact: "Kente is woven in narrow strips, with named patterns and colours carrying histories and meanings." },
    { category: "Celebration", question: "At a Nigerian celebration, what does ‘aso ebi’ usually describe?", options: [{ label: "Co-ordinated cloth or dress worn by a family or social group", points: 10 }, { label: "The last dance of the evening", points: 2 }, { label: "A gift for the oldest guest", points: 1 }, { label: "A pepper blend", points: 0 }], fact: "Aso ebi means family cloth and expresses solidarity and belonging at social occasions." },
    { category: "Symbols", question: "Adinkra are best described as what?", options: [{ label: "Visual symbols expressing ideas, values and proverbs", points: 10 }, { label: "A family of drums", points: 1 }, { label: "Beads used only for age counting", points: 2 }, { label: "A ceremonial bread", points: 0 }], fact: "Adinkra symbols communicate concepts about life, leadership, character, history and philosophy." },
    { category: "Music", question: "Highlife music first became especially associated with which country?", options: [{ label: "Ghana", points: 10 }, { label: "Libya", points: 0 }, { label: "Lesotho", points: 0 }, { label: "Ethiopia", points: 1 }], fact: "Highlife developed in Ghana and spread widely, combining local musical forms with brass-band and guitar influences." },
    { category: "Instruments", question: "How does a talking drum player change its pitch?", options: [{ label: "By squeezing tension cords under the arm", points: 10 }, { label: "By filling it with water", points: 1 }, { label: "By changing wooden sticks", points: 2 }, { label: "By turning away from the audience", points: 0 }], fact: "Squeezing the drum's tension cords changes the skin tension and lets the instrument imitate tonal speech patterns." },
    { category: "Food", question: "Fonio is what kind of food?", options: [{ label: "A tiny ancient grain", points: 10 }, { label: "A smoked river fish", points: 2 }, { label: "A fermented milk drink", points: 1 }, { label: "A groundnut stew", points: 1 }], fact: "Fonio is a small-grained cereal cultivated in parts of West Africa and valued for cooking quickly." },
    { category: "History", question: "Timbuktu became famous as a major centre of learning in which present-day country?", options: [{ label: "Mali", points: 10 }, { label: "Gabon", points: 0 }, { label: "Namibia", points: 0 }, { label: "Kenya", points: 1 }], fact: "Timbuktu flourished as an intellectual, spiritual and trading centre, with major manuscript and scholarly traditions." },
    { category: "Music", question: "Mbalax is most closely associated with which country?", options: [{ label: "Senegal", points: 10 }, { label: "Egypt", points: 1 }, { label: "Botswana", points: 0 }, { label: "Rwanda", points: 1 }], fact: "Mbalax is a Senegalese popular music style shaped by sabar drum rhythms and modern instrumentation." },
    { category: "Art", question: "The ancient Nok culture is especially celebrated for figures made from what?", options: [{ label: "Terracotta", points: 10 }, { label: "Ice", points: 0 }, { label: "Marble only", points: 1 }, { label: "Glass mosaic", points: 1 }], fact: "Nok terracotta sculpture from what is now central Nigeria includes distinctive human and animal figures." },
    { category: "Food History", question: "The name ‘jollof’ is historically linked to which West African kingdom or region?", options: [{ label: "Jolof in the Senegambian region", points: 10 }, { label: "Kongo in Central Africa", points: 1 }, { label: "Aksum in the Horn", points: 0 }, { label: "Mapungubwe in Southern Africa", points: 0 }], fact: "The dish's name is widely linked to Jolof or Wolof history in the Senegambian region, long before today's friendly jollof rivalries." },
  ],
  east: [
    { category: "Food", question: "Which tiny grain is traditionally used to make Ethiopian and Eritrean injera?", options: [{ label: "Teff", points: 10 }, { label: "Rice", points: 0 }, { label: "Fonio", points: 2 }, { label: "Barley sugar", points: 0 }], fact: "Teff flour gives injera its distinctive flavour and texture, although local recipes can also blend grains." },
    { category: "Language", question: "The Swahili saying ‘Haraka haraka haina baraka’ gives which advice?", options: [{ label: "Hurry, hurry has no blessing", points: 10 }, { label: "A guest brings rain", points: 1 }, { label: "Music shortens the road", points: 2 }, { label: "The sea remembers every boat", points: 0 }], fact: "The proverb warns that rushing can spoil a task. Care and patience matter." },
    { category: "Governance", question: "The Gada system is an indigenous socio-political system of which people?", options: [{ label: "The Oromo", points: 10 }, { label: "The Akan", points: 1 }, { label: "The San", points: 1 }, { label: "The Tuareg", points: 1 }], fact: "Gada is a traditional Oromo system that regulates political, social, economic and religious life." },
    { category: "Craft", question: "Uganda's UNESCO-recognised barkcloth craft is ancient among which people?", options: [{ label: "The Baganda", points: 10 }, { label: "The Chewa", points: 1 }, { label: "The Ewe", points: 1 }, { label: "The Shona", points: 1 }], fact: "Baganda craftspeople produce barkcloth from the inner bark of the mutuba tree through a skilled beating process." },
    { category: "Dance", question: "Moutya, danced to a heated goatskin drum, is a living tradition of which islands?", options: [{ label: "Seychelles", points: 10 }, { label: "Zanzibar only", points: 2 }, { label: "Madagascar only", points: 1 }, { label: "Mauritius only", points: 2 }], fact: "Moutya is a Seychellois Creole dance tradition with roots in resistance, dignity and social expression." },
    { category: "Cloth", question: "On the Swahili coast, a kanga often communicates through what extra feature?", options: [{ label: "A printed proverb or message", points: 10 }, { label: "A hidden bell", points: 1 }, { label: "A metal clasp", points: 1 }, { label: "A woven family tree", points: 2 }], fact: "Kanga cloth commonly combines a decorative border, central design and a short Swahili message or proverb." },
    { category: "Art", question: "Tingatinga painting developed in which country?", options: [{ label: "Tanzania", points: 10 }, { label: "Mali", points: 0 }, { label: "Tunisia", points: 0 }, { label: "Angola", points: 1 }], fact: "The brightly coloured style takes its name from Tanzanian painter Edward Saidi Tingatinga." },
    { category: "Ceremony", question: "In the Ethiopian coffee ceremony, what is traditionally roasted in front of guests?", options: [{ label: "Green coffee beans", points: 10 }, { label: "Cocoa pods", points: 1 }, { label: "Tea leaves", points: 1 }, { label: "Sesame cakes", points: 0 }], fact: "The beans are washed, roasted, ground and brewed as part of an extended act of welcome and conversation." },
    { category: "Architecture", question: "The famous churches of Lalibela in Ethiopia were carved primarily from what?", options: [{ label: "Living rock", points: 10 }, { label: "Bamboo", points: 0 }, { label: "Coral blocks", points: 2 }, { label: "Sun-dried brick only", points: 1 }], fact: "Lalibela's monolithic churches were cut down into volcanic rock and remain important pilgrimage sites." },
    { category: "Dance", question: "Adumu, known for its vertical jumping, is associated with which people?", options: [{ label: "Maasai", points: 10 }, { label: "Amazigh", points: 1 }, { label: "Yoruba", points: 1 }, { label: "Kongo", points: 1 }], fact: "Adumu is often described as a jumping dance performed by Maasai warriors within particular ceremonial contexts." },
    { category: "Trade", question: "Which sailing vessel became strongly associated with Indian Ocean trade along the Swahili coast?", options: [{ label: "Dhow", points: 10 }, { label: "Gondola", points: 0 }, { label: "Longship", points: 0 }, { label: "Reed punt", points: 1 }], fact: "Dhows connected coastal East Africa with Arabia, India and wider Indian Ocean trading networks." },
    { category: "Food", question: "Pilau on the Swahili coast is best described as what?", options: [{ label: "Spiced rice cooked with aromatics and often meat or vegetables", points: 10 }, { label: "A sour milk drink", points: 1 }, { label: "A raw fish salad only", points: 2 }, { label: "A millet pancake", points: 1 }], fact: "Swahili pilau reflects centuries of coastal exchange while retaining distinct local recipes and spice balances." },
  ],
  central: [
    { category: "Music", question: "Makossa music is most closely associated with which country?", options: [{ label: "Cameroon", points: 10 }, { label: "Morocco", points: 0 }, { label: "Mozambique", points: 1 }, { label: "Mauritania", points: 0 }], fact: "Makossa developed in Cameroon, especially around Douala, and became internationally influential." },
    { category: "Food", question: "Cameroonian ndolé is named for which key ingredient?", options: [{ label: "Bitter leaves", points: 10 }, { label: "Blue maize", points: 1 }, { label: "Dried dates", points: 0 }, { label: "Teff flour", points: 0 }], fact: "Ndolé combines prepared bitter leaves with groundnuts and may include meat, fish or seafood." },
    { category: "Music", question: "Soukous grew from modern dance music in which cultural area?", options: [{ label: "The two Congos", points: 10 }, { label: "The Nile Delta", points: 1 }, { label: "The Cape winelands", points: 0 }, { label: "The Sahel only", points: 1 }], fact: "Congolese rumba and soukous became celebrated for layered guitars, dance energy and wide African influence." },
    { category: "Textiles", question: "Kuba cloth from the Democratic Republic of the Congo is traditionally made mainly from what?", options: [{ label: "Raffia fibre", points: 10 }, { label: "Silk from mulberry worms", points: 1 }, { label: "Wool felt", points: 1 }, { label: "Papyrus sheets", points: 1 }], fact: "Kuba textiles use raffia in woven, embroidered and appliquéd compositions with complex geometric rhythm." },
    { category: "Storytelling", question: "The mvet is both an epic tradition and what kind of instrument?", options: [{ label: "A harp-zither", points: 10 }, { label: "A brass trumpet", points: 1 }, { label: "A water drum", points: 2 }, { label: "A clay whistle", points: 1 }], fact: "Mvet performance combines a stringed instrument with long-form oral epics among Fang and related communities." },
    { category: "Style", question: "The Sapeurs of Brazzaville and Kinshasa are famous for what?", options: [{ label: "Highly expressive, elegant dressing", points: 10 }, { label: "Carving fishing boats", points: 1 }, { label: "Desert falconry", points: 0 }, { label: "Competitive mask making", points: 2 }], fact: "La Sape is a distinctive culture of dress, presentation and social performance in the Congos." },
    { category: "Voice", question: "Baka forest communities are widely celebrated for which musical feature?", options: [{ label: "Complex polyphonic singing", points: 10 }, { label: "Solo bagpipe marches", points: 1 }, { label: "Opera in Italian", points: 0 }, { label: "Silent dance", points: 0 }], fact: "Interlocking vocal lines and yodelling techniques create rich communal polyphony in Baka music." },
    { category: "Instruments", question: "A likembe or sanza belongs to which instrument family?", options: [{ label: "Lamellaphone or thumb piano", points: 10 }, { label: "Double-reed horn", points: 1 }, { label: "Bowed lute", points: 2 }, { label: "Ceramic bell only", points: 1 }], fact: "Metal or plant-fibre keys are plucked with the thumbs over a resonating body." },
    { category: "Festival", question: "Cameroon's Ngondo festival is especially associated with which communities?", options: [{ label: "The Sawa peoples of the coast", points: 10 }, { label: "The Oromo", points: 1 }, { label: "The Basotho", points: 0 }, { label: "The Hausa", points: 1 }], fact: "Ngondo is a major Sawa cultural gathering in Douala linked to water, ancestry, performance and community." },
    { category: "Art", question: "Fang byeri figures were traditionally connected with what?", options: [{ label: "Guardianship of ancestral relics", points: 10 }, { label: "Measuring rainfall", points: 1 }, { label: "Serving food", points: 1 }, { label: "Marking market prices", points: 0 }], fact: "Byeri reliquary figures were part of ancestral remembrance practices. They are not merely decorative objects." },
    { category: "Heritage", question: "In Kongo traditions, an nkisi is best understood as what?", options: [{ label: "A spiritually empowered object", points: 10 }, { label: "A wedding cake", points: 0 }, { label: "A weaving loom", points: 1 }, { label: "A fishing net", points: 1 }], fact: "Nkisi objects bring together materials, specialist knowledge and spiritual purpose within specific Kongo contexts." },
    { category: "Food", question: "Saka-saka, common in parts of Central Africa, is made primarily from what?", options: [{ label: "Cassava leaves", points: 10 }, { label: "Dried figs", points: 0 }, { label: "Teff", points: 0 }, { label: "Seaweed", points: 1 }], fact: "Cassava leaves are pounded and cooked into richly seasoned dishes known by names including saka-saka and pondu." },
  ],
  north: [
    { category: "Food", question: "UNESCO recognises couscous traditions shared by which group of countries?", options: [{ label: "Algeria, Mauritania, Morocco and Tunisia", points: 10 }, { label: "Egypt, Sudan, Eritrea and Ethiopia", points: 2 }, { label: "Ghana, Togo, Benin and Nigeria", points: 0 }, { label: "Kenya, Uganda, Rwanda and Burundi", points: 0 }], fact: "The shared knowledge around making and eating couscous was inscribed by UNESCO in 2020." },
    { category: "Design", question: "Zellige is a decorative art built from what?", options: [{ label: "Hand-cut glazed tile pieces", points: 10 }, { label: "Knotted fishing rope", points: 1 }, { label: "Painted feathers", points: 0 }, { label: "Carved ivory", points: 1 }], fact: "Zellige artisans assemble small cut tiles into precise geometric mosaic patterns." },
    { category: "Music", question: "Raï music emerged most famously from which country?", options: [{ label: "Algeria", points: 10 }, { label: "Uganda", points: 0 }, { label: "Gabon", points: 0 }, { label: "Eswatini", points: 0 }], fact: "Raï developed in Algeria, especially around Oran, and became a powerful modern popular music form." },
    { category: "Music", question: "Gnawa musical traditions are especially associated with which country?", options: [{ label: "Morocco", points: 10 }, { label: "Botswana", points: 0 }, { label: "Ghana", points: 1 }, { label: "Burundi", points: 0 }], fact: "Gnawa traditions combine music, spiritual practice and histories connected to sub-Saharan African ancestry in Morocco." },
    { category: "Food", question: "Harira is best described as what?", options: [{ label: "A tomato-based soup with pulses and herbs", points: 10 }, { label: "A blue cheese", points: 0 }, { label: "A raw grain salad", points: 1 }, { label: "A date-only sweet", points: 1 }], fact: "Recipes vary, but harira often includes tomatoes, lentils or chickpeas, herbs and spices and is strongly associated with Ramadan in Morocco." },
    { category: "Peoples", question: "Amazigh is the preferred name of peoples also historically called what?", options: [{ label: "Berber", points: 10 }, { label: "Griot", points: 0 }, { label: "Sapeur", points: 0 }, { label: "Maasai", points: 0 }], fact: "Amazigh peoples have diverse languages and communities across North Africa and the Sahara." },
    { category: "Instruments", question: "The oud is which kind of instrument?", options: [{ label: "A short-necked, pear-shaped lute", points: 10 }, { label: "A metal shaker", points: 1 }, { label: "A talking drum", points: 2 }, { label: "A reed flute only", points: 1 }], fact: "The fretless oud is central to many North African and Middle Eastern musical traditions." },
    { category: "Food", question: "Egyptian koshari combines rice, lentils and pasta with what distinctive topping?", options: [{ label: "Tomato sauce and crisp fried onions", points: 10 }, { label: "Melted chocolate", points: 0 }, { label: "Raw mango", points: 1 }, { label: "Smoked salmon", points: 0 }], fact: "Koshari is a beloved Egyptian street food layered with pulses, grains, pasta, spiced tomato sauce and fried onions." },
    { category: "Dress", question: "Why are Tuareg communities sometimes associated with the colour indigo?", options: [{ label: "Indigo-dyed veils and robes", points: 10 }, { label: "Blue-painted houses only", points: 2 }, { label: "A ban on all other colours", points: 0 }, { label: "Blue cattle", points: 0 }], fact: "Indigo-dyed cloth has been especially associated with Tuareg dress, although styles and practices vary." },
    { category: "Geography", question: "Siwa in western Egypt is best known as what?", options: [{ label: "A desert oasis", points: 10 }, { label: "A mountain glacier", points: 0 }, { label: "An Atlantic island", points: 0 }, { label: "A rainforest city", points: 0 }], fact: "Siwa Oasis has distinctive Amazigh heritage, architecture, date palms and salt lakes." },
    { category: "Cities", question: "In a North African city, what does ‘medina’ usually mean?", options: [{ label: "The historic old city or quarter", points: 10 }, { label: "A modern airport", points: 0 }, { label: "A desert well", points: 1 }, { label: "A musical scale", points: 1 }], fact: "Many medinas contain dense lanes, homes, markets, workshops, religious buildings and civic spaces." },
    { category: "Performance", question: "Moroccan tbourida or fantasia celebrates what skill?", options: [{ label: "Synchronised ceremonial horsemanship", points: 10 }, { label: "Deep-sea diving", points: 0 }, { label: "Mountain skiing", points: 0 }, { label: "Shadow puppetry", points: 1 }], fact: "Teams of riders perform a co-ordinated charge and ceremonial rifle discharge, drawing on historic cavalry traditions." },
  ],
  southern: [
    { category: "Philosophy", question: "What idea is at the heart of Ubuntu?", options: [{ label: "A person becomes fully human through other people", points: 10 }, { label: "Success must be pursued alone", points: 0 }, { label: "Wisdom belongs only to elders", points: 2 }, { label: "Silence is always stronger than speech", points: 1 }], fact: "Ubuntu is associated with connectedness, shared humanity, compassion and mutual responsibility." },
    { category: "Custom", question: "In several Southern African societies, lobola traditionally describes what?", options: [{ label: "A negotiated marriage gift between families, historically often involving cattle", points: 10 }, { label: "A sunrise naming ceremony", points: 2 }, { label: "A harvest contest", points: 1 }, { label: "A bride's private savings", points: 0 }], fact: "Practices differ by community. Lobola concerns family relationships and customary marriage, not a price tag on a person." },
    { category: "Dance", question: "South Africa's gumboot dance grew from communication and rhythm among whom?", options: [{ label: "Mine workers", points: 10 }, { label: "Desert caravan guides", points: 0 }, { label: "Coastal fishers", points: 1 }, { label: "Royal praise singers only", points: 2 }], fact: "Workers in South African mines developed percussive movement using boots, bodies and chains." },
    { category: "History", question: "The Shona word ‘Zimbabwe’ is most closely connected to which idea?", options: [{ label: "House or houses of stone", points: 10 }, { label: "Land of a thousand lakes", points: 2 }, { label: "Golden drum", points: 1 }, { label: "Four rivers", points: 0 }], fact: "The monumental dry-stone city of Great Zimbabwe gave the modern country its name." },
    { category: "Art", question: "Ndebele mural traditions are especially famous for what?", options: [{ label: "Bold geometric colour and pattern", points: 10 }, { label: "Ice sculpture", points: 0 }, { label: "Monochrome seascapes", points: 1 }, { label: "Paper lanterns", points: 0 }], fact: "Ndebele women developed highly distinctive painted wall designs, with practices continuing and evolving today." },
    { category: "Dress", question: "Which garment is strongly associated with Basotho identity?", options: [{ label: "The Basotho blanket", points: 10 }, { label: "The kanga", points: 1 }, { label: "The Tuareg tagelmust", points: 0 }, { label: "The Moroccan djellaba", points: 0 }], fact: "Basotho blankets carry named designs and are worn at everyday, ceremonial and national occasions." },
    { category: "Music", question: "The mbira is played by doing what?", options: [{ label: "Plucking metal keys with the thumbs and fingers", points: 10 }, { label: "Blowing across clay pots", points: 1 }, { label: "Striking two horns", points: 0 }, { label: "Bowing one string", points: 1 }], fact: "Mbira music is deeply associated with Shona musical, social and spiritual life in Zimbabwe." },
    { category: "Travel", question: "A mokoro, used in Botswana's Okavango Delta, is what?", options: [{ label: "A slender dugout-style canoe", points: 10 }, { label: "A woven hat", points: 1 }, { label: "A cattle bell", points: 1 }, { label: "A stone tower", points: 0 }], fact: "Mokoro are poled through the Delta's shallow waterways. Many modern versions use durable synthetic materials." },
    { category: "Music", question: "Isicathamiya is best known as which kind of performance?", options: [{ label: "South African male choral singing with soft choreography", points: 10 }, { label: "Solo desert flute", points: 1 }, { label: "Masked stilt dancing", points: 2 }, { label: "Brass-band marching", points: 1 }], fact: "Isicathamiya developed among Zulu migrant-worker communities and combines close harmony with carefully controlled movement." },
    { category: "Food", question: "Bobotie, associated with Cape Malay culinary history, is usually what?", options: [{ label: "Spiced minced meat baked with an egg topping", points: 10 }, { label: "A maize drink", points: 1 }, { label: "A raw fish dish", points: 1 }, { label: "A fruit-only pudding", points: 0 }], fact: "Bobotie reflects layered Cape histories and is commonly seasoned with spices and topped with a savoury custard." },
    { category: "Nature", question: "Marula fruit is traditionally used to make drinks, foods and what other product?", options: [{ label: "Oil", points: 10 }, { label: "Salt", points: 1 }, { label: "Iron", points: 0 }, { label: "Paper money", points: 0 }], fact: "Marula kernels yield a valued oil, while the fruit is eaten fresh and used in juices and fermented drinks." },
    { category: "Heritage", question: "The oldest Southern African rock art traditions are especially associated with which peoples?", options: [{ label: "San communities", points: 10 }, { label: "Vikings", points: 0 }, { label: "Romans", points: 0 }, { label: "Polynesians", points: 0 }], fact: "San rock art records complex spiritual, social and environmental knowledge across thousands of sites." },
  ],
};

export const resultTiers = [
  { min: 0, title: "Culture Curious", cowries: "1,200", emoji: "🌱", line: "You came with curiosity, and curiosity always gets a seat at the table." },
  { min: 30, title: "Story Starter", cowries: "5,000", emoji: "📖", line: "You know enough to begin the story and ask the questions that unlock the good parts." },
  { min: 50, title: "Rhythm Finder", cowries: "12,000", emoji: "🥁", line: "The rhythm found you. Your cultural radar is warming up beautifully." },
  { min: 70, title: "Heritage Connector", cowries: "25,000", emoji: "✨", line: "You connect food, philosophy, art and history with confident flair." },
  { min: 90, title: "Cultural Princess", cowries: "50,000", emoji: "👑", line: "Your knowledge is rich and the family group chat has gone respectfully quiet." },
  { min: 110, title: "Living Library", cowries: "100,000", emoji: "🏆", line: "Negotiations paused. Everyone is listening because your heritage knowledge entered first." },
];
