export type RetentionEntry = Readonly<{category:string;purpose:string;location:string;trigger:string;maximum:string;expiry:string;deletion:string;control:string;active:string}>;
const row = (value: RetentionEntry) => Object.freeze(value);
export const retentionSchedule: readonly RetentionEntry[] = Object.freeze([
  row({category:"Incomplete attempts",purpose:"Resume and securely complete an accepted quiz.",location:"D1 only when the feature and binding are active.",trigger:"Attempt start.",maximum:"The schema requires an expiry; the current browser recovery is 24 hours. The older seven-day documentation proposal is not represented as implemented.",expiry:"Unavailable after its stored server expiry.",deletion:"Deletion/anonymisation readiness exists; no public deletion route is active.",control:"Clear browser recovery; server request information is on /privacy/requests.",active:"Feature-gated; hosted D1 unbound."}),
  row({category:"Completed attempts, answers and private results",purpose:"Authoritative scoring, ownership and result features.",location:"D1 when activated.",trigger:"Authoritative quiz completion.",maximum:"Exactly 90 days from completion.",expiry:"Attempt and result become unavailable; answers follow the owning attempt lifecycle.",deletion:"May become unavailable earlier through valid deletion, anonymisation or revocation lifecycle actions.",control:"Ownership proof may support a request; no automatic deletion route is active.",active:"Feature-gated; hosted D1 unbound."}),
  row({category:"Published results and previews",purpose:"Provide an explicitly published result link and safe social metadata.",location:"D1 result plus generated preview store when bound.",trigger:"The original authoritative quiz completion, not publication.",maximum:"Exactly 90 days from completion; publication never extends, restarts or removes expiry.",expiry:"Public page and metadata return the same neutral unavailable state.",deletion:"Unpublication or valid deletion can end access earlier; external copies and caches are outside application control.",control:"Owner can unpublish with valid ownership proof while the result remains active.",active:"Feature-gated; D1 and R2 unbound."}),
  row({category:"Challenges",purpose:"Provide a verified score-to-beat invitation.",location:"D1 when activated.",trigger:"Challenge creation.",maximum:"30 days or the inviter result’s remaining life, whichever ends first.",expiry:"Neutral unavailable response; accepted play is also bounded by its own expiry.",deletion:"Capability-based revocation is implemented at service level; no general public deletion form is promised.",control:"Use retained ownership/revocation proof where the supported flow is available.",active:"Feature-gated; hosted D1 unbound."}),
  row({category:"Challenge attempts",purpose:"Idempotent acceptance and authoritative comparison.",location:"D1 when activated.",trigger:"Challenge acceptance.",maximum:"Acceptance is capped at 24 hours and never beyond the challenge expiry; broader record cleanup needs final operational approval.",expiry:"Cannot complete after acceptance, challenge, attempt or source-result authority expires.",deletion:"Anonymisation/deletion fields exist; no automated public route.",control:"See /privacy/requests.",active:"Feature-gated; hosted D1 unbound."}),
  row({category:"Referral, share and analytics events",purpose:"Consented first-party product measurement.",location:"D1 when analytics is activated.",trigger:"Eligible event after affirmative consent.",maximum:"Raw version-1 events: 30 days from occurrence.",expiry:"Bounded retention operation deletes expired raw rows.",deletion:"Withdrawal stops new collection immediately; existing server records follow approved retention/request handling.",control:"Do not allow analytics; clear the local credential; use /privacy/requests for server-held data questions.",active:"Off by default; hosted D1 unbound."}),
  row({category:"Analytics consent preference",purpose:"Remember the current versioned choice.",location:"Browser localStorage; server consent record only after acceptance and activation.",trigger:"Allow or Do not allow choice.",maximum:"180 days. Analytics session credential: 24 hours.",expiry:"Fresh choice required after expiry or a materially changed notice version.",deletion:"Withdrawal removes local analytics credentials immediately; local clear removes the preference without emitting analytics.",control:"Privacy choices.",active:"Controls implemented; analytics off by default."}),
  row({category:"Daily challenges, streaks, parties and party players",purpose:"Future scheduled and group-play features.",location:"Schema only; no active product flow.",trigger:"Not active.",maximum:"No production retention is claimed; earlier documentation values remain proposals pending activation review.",expiry:"Not applicable while inactive.",deletion:"Must be approved before activation.",control:"None required while inactive.",active:"Inactive."}),
  row({category:"Royal Reveal pending orders",purpose:"Safely complete a requested payment lifecycle.",location:"D1 when commerce is activated; opaque return reference in sessionStorage.",trigger:"Order creation after separate immediate-delivery consent.",maximum:"Pending authority: 30 minutes. Commerce audit records are configured for 400 days pending professional/statutory review.",expiry:"Expired pending orders cannot start or prove entitlement.",deletion:"Controlled retention/deletion fields; refund and dispute states remain auditable.",control:"Clear the local return reference; contact route must be configured before activation.",active:"Commerce off by default; hosted D1 unbound."}),
  row({category:"Royal Reveal entitlements and webhook replay records",purpose:"Grant result-bound media generation and make verified webhook handling idempotent.",location:"D1 when commerce is activated.",trigger:"Verified payment webhook.",maximum:"Record retention is configured for 400 days. Ordinary regeneration requires the result to remain active, at most 90 days from quiz completion; the protected return-status flow may finish a verified payment already in progress.",expiry:"Normal regeneration becomes unavailable when the result expires; full refund or dispute can revoke earlier. Payment-return continuity does not extend public result availability.",deletion:"Downloaded files remain on the purchaser’s device until they delete them.",control:"Refund/dispute process and privacy-request route require configured contacts before activation.",active:"Commerce off by default; hosted D1 unbound."}),
  row({category:"Browser quiz and nomination state",purpose:"Recovery, best scores, safe nomination handoff and functional ownership.",location:"localStorage and sessionStorage.",trigger:"Requested feature use.",maximum:"Quiz recovery and anonymous credential: 24 hours; nomination state: tab session; best scores: until cleared.",expiry:"Invalid or expired records are ignored and removed where implemented.",deletion:"Explicit allowlisted local clear.",control:"Privacy choices → Clear my local data.",active:"Active where the related feature is used."}),
  row({category:"Private photographs and generated media",purpose:"Local portrait, video and certificate generation.",location:"Browser memory, short-lived object URLs and user-selected downloads.",trigger:"Deliberate file selection or media action.",maximum:"Private photo: 30 minutes in memory; generated object URLs: until immediate cleanup or component close; downloads: device-controlled.",expiry:"Application memory and object URLs are released; downloaded files are unaffected.",deletion:"Remove photo, clear local data, close page, or delete downloaded files using device controls.",control:"Direct controls at the point of use and in Privacy choices.",active:"Private photo active; other media feature-gated."}),
]);
