"use client";
/* eslint-disable @next/next/no-img-element -- approved local avatar preview; no remote image loader or upload */
import { useEffect,useMemo,useRef,useState } from "react";
import StoryVideoPanel from "./StoryVideoPanel";
import { resolveApprovedAvatar } from "./avatarRegistry.ts";
import { downloadRoyalMedia,prepareRoyalCertificate,prepareRoyalPortrait,royalStoryProjection,shareRoyalMedia,ROYAL_PORTRAIT_STYLES,type RoyalPortraitStyle } from "./royalRevealMedia.ts";
import { createRoyalRevealProjection } from "./royalRevealProjection.ts";
import type { RoyalRevealReviewScenario } from "./royalRevealReview.ts";

export default function RoyalRevealPack({entitlement,reviewScenario}:Readonly<{entitlement:unknown;reviewScenario?:RoyalRevealReviewScenario}>){
 const projection=useMemo(()=>createRoyalRevealProjection(entitlement),[entitlement]);const certificateRef=useRef<HTMLCanvasElement>(null);const [status,setStatus]=useState("Your Royal Reveal files are generated only on this device.");const [busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{if(!projection||!certificateRef.current||!(["certificate","active","succeeded"] as string[]).includes(reviewScenario||""))return;void prepareRoyalCertificate(certificateRef.current,projection,new Date("2026-08-26T12:00:00Z")).catch(()=>setStatus("The certificate preview could not be prepared."));},[projection,reviewScenario]);
 if(!projection)return <div className="royal-reveal-locked" role="status"><b>Royal Reveal unavailable</b><span>A current entitlement for this exact result is required.</span></div>;
 const makePortrait=async(style:RoyalPortraitStyle,share=false)=>{setBusy(style);try{const canvas=document.createElement("canvas");const media=await prepareRoyalPortrait(canvas,projection,style);if(share){const outcome=await shareRoyalMedia(media,`${projection.resultTitle} — Royal Reveal`);setStatus(outcome==="shared"?"The device share sheet completed its handoff.":"Direct file sharing is unavailable, so the portrait was downloaded.");}else{downloadRoyalMedia(media);setStatus(`${media.filename} download started.`);}}catch{setStatus("That portrait could not be prepared. Try again.");}finally{setBusy(null);}};
 const certificate=async(print=false)=>{if(!certificateRef.current)return;setBusy("certificate");try{const media=await prepareRoyalCertificate(certificateRef.current,projection);if(print)window.print();else downloadRoyalMedia(media);setStatus(print?"Print options opened for your certificate.":`${media.filename} download started.`);}catch{setStatus("The certificate could not be prepared. Try again.");}finally{setBusy(null);}};
 const labels:Record<RoyalPortraitStyle,string>={royal_gold:"Royal Gold",cowrie_crown:"Cowrie Crown",indigo_celebration:"Indigo Celebration"};
 return <section className="royal-pack" aria-labelledby="royal-pack-title"><header><p>Payment verified • one-off purchase</p><h3 id="royal-pack-title">Your Royal Reveal Pack</h3><span>£1.99 paid • no subscription</span></header><p className="royal-pack-safeguard">{projection.safeguard}</p>
  <div className="royal-portrait-grid">{ROYAL_PORTRAIT_STYLES.map((style)=><article key={style} className={`royal-portrait-card style-${style}`}><div className="royal-portrait-preview"><span>{labels[style]}</span><img src={resolveApprovedAvatar(projection.avatarId).src} alt=""/><b>{projection.score}/{projection.maximumScore}</b><small>{projection.resultTitle}</small><em>{projection.safeguard}</em></div><h4>{labels[style]}</h4><p>1080 × 1350 PNG</p><div><button type="button" onClick={()=>void makePortrait(style)} disabled={busy===style}>Download</button><button type="button" onClick={()=>void makePortrait(style,true)} disabled={busy===style}>Share file</button></div></article>)}</div>
  <article className="royal-certificate"><div><p>Print-quality A4 PNG</p><h4>Royal Culture Score Certificate</h4><span>2480 × 3508 • entertainment and learning only</span><div><button type="button" onClick={()=>void certificate(false)} disabled={busy==="certificate"}>Download certificate</button><button type="button" onClick={()=>void certificate(true)} disabled={busy==="certificate"}>Print certificate</button></div></div><canvas ref={certificateRef} width={2480} height={3508} aria-label={`Royal Culture Score Certificate preview for ${projection.score} out of ${projection.maximumScore}`}/></article>
  <StoryVideoPanel projection={royalStoryProjection(projection)} entitlement={projection} surface="result" soundEnabled={false} onUseStatic={async()=>{setStatus("The free static Story image remains available from the Share Centre.");}} forceUnsupported={reviewScenario==="unsupported_video"}/>
  <p className="royal-pack-status" role="status" aria-live="polite">{status}</p><p className="royal-pack-privacy">Approved avatar and regional artwork only. Private photos, payment details and identifiers are never included or uploaded.</p></section>;
}
