import { resolveApprovedAvatar } from "./avatarRegistry.ts";
import { regions } from "./publicGameData.ts";
import { requireRoyalRevealProjection } from "./royalRevealProjection.ts";

export const ROYAL_PORTRAIT_WIDTH=1080; export const ROYAL_PORTRAIT_HEIGHT=1350; export const ROYAL_CERTIFICATE_WIDTH=2480; export const ROYAL_CERTIFICATE_HEIGHT=3508;
export const ROYAL_PORTRAIT_STYLES=Object.freeze(["royal_gold","cowrie_crown","indigo_celebration"] as const);
export type RoyalPortraitStyle=(typeof ROYAL_PORTRAIT_STYLES)[number];
export type PreparedRoyalMedia=Readonly<{blob:Blob;file:File;filename:string;mimeType:"image/png";width:number;height:number}>;

const styleLabels:Record<RoyalPortraitStyle,string>={royal_gold:"Royal Gold",cowrie_crown:"Cowrie Crown",indigo_celebration:"Indigo Celebration"};
const palettes:Record<RoyalPortraitStyle,readonly [string,string,string]>={royal_gold:["#241005","#f0a11a","#fff2bd"],cowrie_crown:["#15392f","#f6dfad","#d96f32"],indigo_celebration:["#15133f","#6d60c5","#ffe6a6"]};
function regionAsset(edition:string){return `/regions/${edition==="south"?"southern":edition}-africa.webp`;}
function safeFilename(value:string){return value.replaceAll("_","-");}
export function royalPortraitFilename(style:RoyalPortraitStyle,edition:string){return `whats-your-bride-price-${edition}-${safeFilename(style)}-portrait.png`;}
export function royalCertificateFilename(edition:string){return `whats-your-bride-price-${edition}-royal-culture-score-certificate.png`;}
async function image(src:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const value=new Image();value.decoding="async";value.onload=()=>resolve(value);value.onerror=()=>reject(new Error("royal_asset_unavailable"));value.src=src;});}
function fit(ctx:CanvasRenderingContext2D,value:CanvasImageSource,x:number,y:number,w:number,h:number){ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();const source=value as HTMLImageElement;const ratio=Math.max(w/source.width,h/source.height);const sw=source.width*ratio,sh=source.height*ratio;ctx.drawImage(value,x+(w-sw)/2,y+(h-sh)/2,sw,sh);ctx.restore();}
function text(ctx:CanvasRenderingContext2D,value:string,x:number,y:number,max:number,lineHeight:number){const words=value.split(" ");let line="",cursor=y;for(const word of words){const next=`${line}${line?" ":""}${word}`;if(ctx.measureText(next).width>max&&line){ctx.fillText(line,x,cursor);line=word;cursor+=lineHeight;}else line=next;}if(line)ctx.fillText(line,x,cursor);}
async function png(canvas:HTMLCanvasElement,filename:string,width:number,height:number):Promise<PreparedRoyalMedia>{const blob=await new Promise<Blob|null>((resolve)=>canvas.toBlob(resolve,"image/png"));if(!blob||blob.type!=="image/png")throw new Error("royal_media_failed");return Object.freeze({blob,file:new File([blob],filename,{type:"image/png",lastModified:Date.now()}),filename,mimeType:"image/png",width,height});}

export async function prepareRoyalPortrait(canvas:HTMLCanvasElement,projectionValue:unknown,style:RoyalPortraitStyle):Promise<PreparedRoyalMedia>{
  const projection=requireRoyalRevealProjection(projectionValue);if(!ROYAL_PORTRAIT_STYLES.includes(style))throw new Error("royal_portrait_style_invalid");canvas.width=ROYAL_PORTRAIT_WIDTH;canvas.height=ROYAL_PORTRAIT_HEIGHT;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("royal_canvas_unavailable");const [dark,accent,light]=palettes[style];const [avatar,art]=await Promise.all([image(resolveApprovedAvatar(projection.avatarId).src),image(regionAsset(projection.edition))]);
  const gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,dark);gradient.addColorStop(1,accent);ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);ctx.globalAlpha=.22;fit(ctx,art,0,0,1080,1350);ctx.globalAlpha=1;ctx.strokeStyle=light;ctx.lineWidth=12;ctx.strokeRect(42,42,996,1266);ctx.fillStyle=dark;ctx.fillRect(110,118,860,142);ctx.fillStyle=light;ctx.textAlign="center";ctx.font="800 36px Georgia";ctx.fillText("WHAT’S YOUR BRIDE PRICE?",540,174);ctx.font="700 29px Arial";ctx.fillText(styleLabels[style].toUpperCase(),540,222);ctx.save();ctx.beginPath();ctx.arc(540,635,300,0,Math.PI*2);ctx.clip();fit(ctx,avatar,240,335,600,600);ctx.restore();ctx.strokeStyle=light;ctx.lineWidth=16;ctx.beginPath();ctx.arc(540,635,308,0,Math.PI*2);ctx.stroke();ctx.fillStyle=light;ctx.font="800 39px Georgia";ctx.fillText(regions[projection.edition].name.toUpperCase(),540,1010);ctx.font="900 72px Georgia";ctx.fillText(`${projection.score} / ${projection.maximumScore}`,540,1090);ctx.font="700 41px Arial";ctx.fillText(projection.resultTitle,540,1154);ctx.font="700 27px Arial";text(ctx,projection.safeguard,540,1228,880,36);return png(canvas,royalPortraitFilename(style,projection.edition),1080,1350);
}

export async function prepareRoyalCertificate(canvas:HTMLCanvasElement,projectionValue:unknown,generationDate=new Date()):Promise<PreparedRoyalMedia>{
  const projection=requireRoyalRevealProjection(projectionValue);canvas.width=ROYAL_CERTIFICATE_WIDTH;canvas.height=ROYAL_CERTIFICATE_HEIGHT;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("royal_canvas_unavailable");const [avatar,art]=await Promise.all([image(resolveApprovedAvatar(projection.avatarId).src),image(regionAsset(projection.edition))]);ctx.fillStyle="#fff9e8";ctx.fillRect(0,0,2480,3508);ctx.globalAlpha=.1;fit(ctx,art,0,0,2480,3508);ctx.globalAlpha=1;ctx.strokeStyle="#8c4c14";ctx.lineWidth=22;ctx.strokeRect(100,100,2280,3308);ctx.strokeStyle="#e0a126";ctx.lineWidth=8;ctx.strokeRect(140,140,2200,3228);ctx.fillStyle="#31180a";ctx.textAlign="center";ctx.font="800 74px Georgia";ctx.fillText("WHAT’S YOUR BRIDE PRICE?",1240,430);ctx.font="900 130px Georgia";ctx.fillText("Royal Culture Score",1240,650);ctx.fillText("Certificate",1240,800);ctx.font="600 48px Arial";ctx.fillText("A playful recognition of cultural knowledge",1240,930);ctx.save();ctx.beginPath();ctx.arc(1240,1480,390,0,Math.PI*2);ctx.clip();fit(ctx,avatar,850,1090,780,780);ctx.restore();ctx.strokeStyle="#d89a22";ctx.lineWidth=20;ctx.beginPath();ctx.arc(1240,1480,400,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#31180a";ctx.font="800 72px Georgia";ctx.fillText(`${regions[projection.edition].name} Edition`,1240,2040);ctx.font="900 155px Georgia";ctx.fillText(`${projection.score} / ${projection.maximumScore}`,1240,2255);ctx.font="800 82px Arial";ctx.fillText(projection.resultTitle,1240,2405);ctx.font="600 46px Arial";ctx.fillText(`Generated ${generationDate.toISOString().slice(0,10)}`,1240,2580);ctx.font="700 48px Arial";text(ctx,projection.safeguard,1240,2840,1900,66);ctx.font="600 35px Arial";ctx.fillText("For entertainment and learning — not a legal, educational or professional certification.",1240,3180);return png(canvas,royalCertificateFilename(projection.edition),2480,3508);
}

export function downloadRoyalMedia(media:PreparedRoyalMedia){const url=URL.createObjectURL(media.blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=media.filename;anchor.rel="noopener";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
export async function shareRoyalMedia(media:PreparedRoyalMedia,title:string):Promise<"shared"|"downloaded">{if(typeof navigator.share!=="function"||typeof navigator.canShare!=="function"||!navigator.canShare({files:[media.file]})){downloadRoyalMedia(media);return"downloaded";}await navigator.share({title,files:[media.file]});return"shared";}
export function royalStoryProjection(projectionValue:unknown){const projection=requireRoyalRevealProjection(projectionValue);const region=regions[projection.edition];const avatar=resolveApprovedAvatar(projection.avatarId);return Object.freeze({edition:projection.edition,editionLabel:region.name,score:projection.score,maximumScore:projection.maximumScore,resultTitle:projection.resultTitle,avatarId:projection.avatarId,avatarAsset:avatar.src,regionalArtwork:regionAsset(projection.edition),theme:Object.freeze({base:region.palette[0],accent:region.palette[1],dark:region.palette[2],mark:region.mark}),mastery:projection.score>=9,safeguard:projection.safeguard,publicResultUrl:null});}
