"use client";
import { useEffect,useMemo,useState } from "react";
import { emitAnalyticsLocalEvent } from "./analyticsLocal.ts";
import { PRODUCT_SAFEGUARD,RESULT_TIER_TITLES } from "./productSafeguards.ts";
import RoyalRevealPack from "./RoyalRevealPack.tsx";
import { royalRevealReviewContext,royalRevealReviewEnabled,type RoyalRevealReviewScenario } from "./royalRevealReview.ts";
import type { RegionKey } from "./gameData.ts";

const consentNotice="I request immediate access to the digital Royal Reveal Pack after payment and understand that once digital delivery begins, my statutory cancellation right may be affected.";
function fixtureEntitlement(edition:RegionKey,score:number,total:number,avatarId:string){return {active:true,productKey:"royal_reveal_v1",resultSlug:royalRevealReviewContext.resultSlug,edition,score,maximumScore:total,resultTitle:RESULT_TIER_TITLES[score>=9?3:score>=7?2:score>=4?1:0],avatarId};}
export default function RoyalRevealOffer({edition,score,total,avatarId,reviewScenario,purchaseContext}:Readonly<{edition:RegionKey;score:number;total:number;avatarId:string;reviewScenario?:RoyalRevealReviewScenario;purchaseContext?:Readonly<{resultSlug:string;anonymousSessionCredential:string}>}>){
 const initial=reviewScenario==="processing"?"processing":reviewScenario==="failed"?"failed":reviewScenario==="refunded"?"refunded":(["succeeded","active","portraits","certificate","unsupported_video"] as string[]).includes(reviewScenario||"")?"active":"offer";const [state,setState]=useState<"offer"|"processing"|"failed"|"active"|"refunded">(initial);const [consent,setConsent]=useState(false);const [error,setError]=useState(reviewScenario==="consent_error"?"Please confirm the immediate digital delivery request before continuing.":"");const entitlement=useMemo(()=>state==="active"?fixtureEntitlement(edition,score,total,avatarId):null,[state,edition,score,total,avatarId]);
 useEffect(()=>{emitAnalyticsLocalEvent({name:"offer_view",properties:{edition,surface:"result"}});},[edition]);
 if(state==="active"&&entitlement)return <RoyalRevealPack entitlement={entitlement} reviewScenario={reviewScenario}/>;
 if(state==="processing")return <section className="royal-offer royal-state" role="status" aria-live="polite"><span className="royal-spinner" aria-hidden="true"/><h3>Confirming your payment</h3><p>Stripe’s verified webhook decides access. This page cannot grant the pack from a redirect or query parameter.</p><button type="button" onClick={()=>setState("offer")}>Return to free result</button></section>;
 if(state==="failed"||state==="refunded")return <section className="royal-offer royal-state is-error" role="status"><h3>{state==="refunded"?"Royal Reveal access revoked":"Payment not completed"}</h3><p>{state==="refunded"?"A verified full refund revoked this result’s entitlement. Your free result and sharing options remain available.":"No charge was confirmed and no entitlement was created. You can retry safely or keep the free result."}</p><button type="button" onClick={()=>setState("offer")}>{state==="failed"?"Try again":"Continue with free result"}</button></section>;
 const unlock=async()=>{if(!consent){setError("Please confirm the immediate digital delivery request before continuing.");return;}setError("");if(royalRevealReviewEnabled){setState("processing");window.setTimeout(()=>setState("active"),450);return;}if(!purchaseContext){setError("Checkout is not active. Your free result remains available.");return;}try{const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);const idempotencyKey=[...bytes].map((byte)=>byte.toString(16).padStart(2,"0")).join("");const response=await fetch("/commerce/orders",{method:"POST",mode:"same-origin",credentials:"omit",referrerPolicy:"no-referrer",headers:{"content-type":"application/json"},body:JSON.stringify({productKey:"royal_reveal_v1",resultSlug:purchaseContext.resultSlug,anonymousSessionCredential:purchaseContext.anonymousSessionCredential,idempotencyKey,immediateDeliveryConsent:true,consentNoticeVersion:"royal-reveal-immediate-delivery-v1"})});const result=await response.json() as Record<string,unknown>;if(!response.ok||typeof result.publicOrderReference!=="string"||!/^rr_[0-9a-f]{32}$/.test(result.publicOrderReference)||typeof result.paymentLinkUrl!=="string")throw new Error("checkout_unavailable");const url=new URL(result.paymentLinkUrl);if(url.protocol!=="https:"||url.hostname!=="buy.stripe.com"||url.searchParams.get("client_reference_id")!==result.publicOrderReference||[...url.searchParams].length!==1)throw new Error("checkout_url_invalid");sessionStorage.setItem("wybp-royal-reveal-pending-v1",JSON.stringify({version:1,publicOrderReference:result.publicOrderReference}));emitAnalyticsLocalEvent({name:"checkout_start",properties:{edition,surface:"result"}});location.assign(url.toString());}catch{setError("Checkout could not start. Your free result remains available; please try again later.");}};
 return <section className="royal-offer" aria-labelledby="royal-offer-title"><div className="royal-offer-crown" aria-hidden="true">♛</div><p className="royal-eyebrow">Royal Reveal Pack • £1.99 GBP</p><h3 id="royal-offer-title">Make your reveal unforgettable</h3><p className="royal-offer-copy">Unlock your animated Story video, premium portrait styles and official Royal Culture Score Certificate for £1.99.</p><ul><li>Five-second 1080 × 1920 Story/Reel video</li><li>Royal Gold, Cowrie Crown and Indigo Celebration portraits — 1080 × 1350 PNG</li><li>Print-quality 2480 × 3508 Royal Culture Score Certificate</li><li>Individual downloads, native file sharing and static video fallback</li></ul><div className="royal-price"><b>£1.99</b><span>One-off payment<br/>No subscription</span></div><p className="royal-offer-safeguard">{PRODUCT_SAFEGUARD}</p><label className="royal-delivery-consent"><input type="checkbox" checked={consent} onChange={(event)=>{setConsent(event.target.checked);setError("");}}/><span>{consentNotice}</span></label>{error&&<p className="royal-offer-error" role="alert">{error}</p>}<div className="royal-offer-actions"><button type="button" className="royal-unlock" onClick={()=>void unlock()}>Unlock for £1.99</button><a href="#free-result-actions">Continue with free result</a></div><p className="royal-offer-honesty">The free quiz, basic result, nominations, challenge links, copy-link sharing and static result remain available without payment.</p></section>;
}
