export const STORAGE_NOTICE_VERSION = "privacy-storage-notice-v1" as const;
export const PRIVACY_CLEAR_EVENT = "wybp:privacy-local-data-cleared" as const;

export type StorageTechnology =
  | "localStorage"
  | "sessionStorage"
  | "memory"
  | "object_url"
  | "url_parameter"
  | "history_state"
  | "clipboard"
  | "download"
  | "cookie"
  | "indexed_db"
  | "cache_storage"
  | "service_worker"
  | "third_party_site";

export type StorageInventoryEntry = Readonly<{
  key: string;
  name: string;
  technology: StorageTechnology;
  browserKey: string | null;
  keyPattern: string | null;
  party: "first_party" | "third_party" | "platform";
  provider: string;
  purpose: string;
  category: "required_functionality" | "optional_analytics" | "external_after_action" | "not_installed";
  data: string;
  trigger: string;
  existsBeforeChoice: boolean;
  requiresAnalyticsConsent: boolean;
  strictlyFunctional: boolean;
  retention: string;
  leavesDevice: boolean;
  userCanClear: boolean;
  clearing: string;
  sourceModules: readonly string[];
  noticeVersion: typeof STORAGE_NOTICE_VERSION;
  state: "enabled" | "feature_gated" | "not_installed" | "provider_controlled";
}>;

const entry = (value: Omit<StorageInventoryEntry, "noticeVersion">): StorageInventoryEntry =>
  Object.freeze({ ...value, sourceModules: Object.freeze([...value.sourceModules]), noticeVersion: STORAGE_NOTICE_VERSION });

export const storageInventory: readonly StorageInventoryEntry[] = Object.freeze([
  entry({ key:"regional_best_scores",name:"Regional best scores",technology:"localStorage",browserKey:"wybp-region-scores",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Remember optional device-local best scores.",category:"required_functionality",data:"Region keys and best numeric scores.",trigger:"After a quiz result.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Until cleared by the user or browser.",leavesDevice:false,userCanClear:true,clearing:"Privacy choices → Clear my local data.",sourceModules:["app/BridePriceGame.tsx"],state:"enabled" }),
  entry({ key:"quiz_recovery",name:"Quiz recovery",technology:"localStorage",browserKey:"wybp-active-quiz-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Restore an unfinished quiz in the same tab.",category:"required_functionality",data:"Edition, approved avatar, question position, selected option indexes and controlled attribution.",trigger:"After quiz play begins.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Up to 24 hours from the last saved update; requires the matching tab key.",leavesDevice:false,userCanClear:true,clearing:"Privacy choices → Clear my local data.",sourceModules:["app/quizRecovery.ts","app/BridePriceGame.tsx"],state:"enabled" }),
  entry({ key:"quiz_recovery_tab",name:"Quiz recovery tab match",technology:"sessionStorage",browserKey:"wybp-active-quiz-instance-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Limit quiz recovery to the tab that created it.",category:"required_functionality",data:"Random quiz instance identifier.",trigger:"When quiz recovery is written.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Current tab session and no longer than the matching 24-hour recovery.",leavesDevice:false,userCanClear:true,clearing:"Privacy choices → Clear my local data.",sourceModules:["app/quizRecovery.ts"],state:"enabled" }),
  entry({ key:"anonymous_session",name:"Anonymous functional session",technology:"sessionStorage",browserKey:"wybp-anonymous-session-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Prove anonymous ownership for requested result, challenge and commerce operations without an account.",category:"required_functionality",data:"A random raw tab credential and its creation and expiry times. Public notices never expose its value.",trigger:"When the application prepares an ownership-dependent feature.",existsBeforeChoice:true,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"24 hours, then rotated; also ends when cleared or the tab session is discarded.",leavesDevice:true,userCanClear:true,clearing:"Privacy choices → Clear my local data. Server-held records are separate.",sourceModules:["app/anonymousSession.ts","app/BridePriceGame.tsx","app/royal-reveal/return/RoyalRevealReturnClient.tsx"],state:"enabled" }),
  entry({ key:"analytics_preference",name:"Analytics preference",technology:"localStorage",browserKey:"wybp-analytics-consent-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Remember an Allow or Do not allow choice for optional first-party analytics.",category:"optional_analytics",data:"Choice, notice version, decision time and expiry time.",trigger:"Only after the user makes a choice.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"180 days from the choice; a new notice version requires a fresh choice.",leavesDevice:false,userCanClear:true,clearing:"Withdraw in Privacy choices or clear local data.",sourceModules:["app/analyticsPreference.ts","app/AnalyticsConsent.tsx"],state:"feature_gated" }),
  entry({ key:"analytics_session",name:"Analytics session credential",technology:"sessionStorage",browserKey:"wybp-analytics-session-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Link allowlisted first-party events within one consented analytics session.",category:"optional_analytics",data:"A random raw analytics credential and creation and expiry times.",trigger:"Only after affirmative analytics consent.",existsBeforeChoice:false,requiresAnalyticsConsent:true,strictlyFunctional:false,retention:"24 hours, or until withdrawal or local clearing.",leavesDevice:true,userCanClear:true,clearing:"Do not allow analytics or Clear my local data.",sourceModules:["app/analyticsPreference.ts","app/AnalyticsConsent.tsx"],state:"feature_gated" }),
  entry({ key:"analytics_seen",name:"Analytics event deduplication",technology:"sessionStorage",browserKey:"wybp-analytics-seen-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Avoid counting selected consented events twice in one tab.",category:"optional_analytics",data:"Up to 40 controlled deduplication labels; no names, codes or credentials.",trigger:"Only after affirmative analytics consent and an eligible event.",existsBeforeChoice:false,requiresAnalyticsConsent:true,strictlyFunctional:false,retention:"Current analytics session, no more than 24 hours, or until withdrawal or clearing.",leavesDevice:false,userCanClear:true,clearing:"Do not allow analytics or Clear my local data.",sourceModules:["app/analyticsPreference.ts","app/AnalyticsConsent.tsx"],state:"feature_gated" }),
  entry({ key:"nomination_snapshot",name:"Nomination handoff state",technology:"sessionStorage",browserKey:null,keyPattern:"wybp-nomination-v1:{safe scope}",party:"first_party",provider:"What’s Your Bride Price?",purpose:"Restore three deliberate nomination handoffs for the current result.",category:"required_functionality",data:"Safe public challenge projection, completed slot numbers and save time.",trigger:"When a user creates or reuses a challenge and nominates people.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Current tab session or until local clearing; public challenge expiry remains authoritative.",leavesDevice:false,userCanClear:true,clearing:"Privacy choices → Clear my local data.",sourceModules:["app/nominationExperience.ts","app/NominateThreePanel.tsx"],state:"feature_gated" }),
  entry({ key:"pending_order",name:"Pending Royal Reveal return reference",technology:"sessionStorage",browserKey:"wybp-royal-reveal-pending-v1",keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Resume protected payment confirmation after deliberate Stripe navigation.",category:"required_functionality",data:"Opaque public order reference only; no Checkout Session ID or payment-card data.",trigger:"Immediately before deliberate Stripe navigation.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Current tab session; removed after verified completion or local clearing. Pending server order expires after 30 minutes.",leavesDevice:true,userCanClear:true,clearing:"Privacy choices → Clear my local data. This does not delete the server order.",sourceModules:["app/RoyalRevealOffer.tsx","app/royal-reveal/return/RoyalRevealReturnClient.tsx"],state:"feature_gated" }),
  entry({ key:"private_photo_memory",name:"Private photograph in memory",technology:"memory",browserKey:null,keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Create an optional local portrait during the current browser session.",category:"required_functionality",data:"Re-encoded image pixels with source metadata removed.",trigger:"Only after the user chooses an image file.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Up to 30 minutes in memory, until removal, replacement, local clearing, restart or page close.",leavesDevice:false,userCanClear:true,clearing:"Remove my photo, restart, close the page, or Clear my local data.",sourceModules:["app/privatePhoto.ts","app/BridePriceGame.tsx"],state:"enabled" }),
  entry({ key:"generated_media_memory",name:"Generated media and object URLs",technology:"object_url",browserKey:null,keyPattern:"blob:{browser-generated value}",party:"first_party",provider:"Browser",purpose:"Preview, download or deliberately share locally generated images and video.",category:"required_functionality",data:"Generated media bytes and short-lived browser object URLs.",trigger:"Only after a user requests media preparation, download or sharing.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"In memory only; URLs are revoked after download, replacement, panel close or component cleanup.",leavesDevice:false,userCanClear:true,clearing:"Close the media surface or Clear my local data; downloaded copies remain under the user’s control.",sourceModules:["app/shareMedia.ts","app/storyVideo.ts","app/StoryVideoPanel.tsx","app/royalRevealMedia.ts"],state:"feature_gated" }),
  entry({ key:"controlled_url_state",name:"Controlled URL state and attribution",technology:"url_parameter",browserKey:null,keyPattern:"edition, nominated, source, utm_source, utm_medium, utm_campaign, ref and approved opaque route codes",party:"first_party",provider:"What’s Your Bride Price?",purpose:"Open a selected edition, safe referral or server-resolved challenge/result route.",category:"required_functionality",data:"Allowlisted tokens and opaque public codes; query values cannot enable protected features or fixtures.",trigger:"Navigation to a link.",existsBeforeChoice:true,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Browser history and any copied link until removed by the user or browser.",leavesDevice:true,userCanClear:true,clearing:"Browser history controls; the application removes payment-return query values immediately.",sourceModules:["app/entryContext.ts","app/challengeEntry.ts","app/publicAppOrigin.ts","app/royal-reveal/return/RoyalRevealReturnClient.tsx"],state:"enabled" }),
  entry({ key:"navigation_history_state",name:"Tab navigation state",technology:"history_state",browserKey:null,keyPattern:"wybpScreen, wybpChallengeAccepted and route state",party:"first_party",provider:"Browser",purpose:"Support Back-button behavior and remove unsafe return-query context.",category:"required_functionality",data:"Screen labels and boolean navigation markers; no raw credentials.",trigger:"During in-app navigation or payment return cleanup.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Current browser history entry.",leavesDevice:false,userCanClear:true,clearing:"Browser history controls or Clear my local data resets the current app entry.",sourceModules:["app/BridePriceGame.tsx","app/challenge/[code]/ChallengeLandingClient.tsx","app/royal-reveal/return/RoyalRevealReturnClient.tsx"],state:"enabled" }),
  entry({ key:"clipboard_write",name:"Clipboard write",technology:"clipboard",browserKey:null,keyPattern:null,party:"first_party",provider:"Browser",purpose:"Copy a safe public or invitation link after a deliberate action.",category:"required_functionality",data:"Only the displayed safe link or controlled share text.",trigger:"Only when the user chooses Copy.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Controlled by the browser, operating system and clipboard manager.",leavesDevice:true,userCanClear:true,clearing:"Use device clipboard controls.",sourceModules:["app/ShareCentre.tsx","app/NominateThreePanel.tsx","app/shareSupport.ts"],state:"enabled" }),
  entry({ key:"file_downloads",name:"Downloaded files",technology:"download",browserKey:null,keyPattern:null,party:"first_party",provider:"Browser and device",purpose:"Save a deliberately generated portrait, video or certificate.",category:"required_functionality",data:"Generated media containing approved result content and, for eligible static portraits, the user-selected local photograph.",trigger:"Only after a download or unsupported-share fallback action.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Until the user deletes the file using device controls.",leavesDevice:false,userCanClear:true,clearing:"Delete through the device. Clear my local data cannot delete downloaded files.",sourceModules:["app/shareMedia.ts","app/storyVideo.ts","app/royalRevealMedia.ts"],state:"feature_gated" }),
  entry({ key:"application_cookies",name:"Application cookies",technology:"cookie",browserKey:null,keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"No application-owned cookie purpose is implemented.",category:"not_installed",data:"None.",trigger:"Not applicable.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:false,retention:"Not applicable.",leavesDevice:false,userCanClear:true,clearing:"No application-owned cookie exists to clear.",sourceModules:[],state:"not_installed" }),
  entry({ key:"indexed_db",name:"Application IndexedDB",technology:"indexed_db",browserKey:null,keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Not installed.",category:"not_installed",data:"None.",trigger:"Not applicable.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:false,retention:"Not applicable.",leavesDevice:false,userCanClear:true,clearing:"No application database exists to clear.",sourceModules:[],state:"not_installed" }),
  entry({ key:"application_caches",name:"Application Cache Storage and service-worker caches",technology:"cache_storage",browserKey:null,keyPattern:null,party:"first_party",provider:"What’s Your Bride Price?",purpose:"Not installed by application code.",category:"not_installed",data:"None.",trigger:"Not applicable.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:false,retention:"Not applicable.",leavesDevice:false,userCanClear:true,clearing:"No application-owned cache is registered.",sourceModules:[],state:"not_installed" }),
  entry({ key:"sites_platform",name:"Sites platform and trusted-dispatch storage",technology:"cookie",browserKey:null,keyPattern:null,party:"platform",provider:"OpenAI Sites / trusted dispatch",purpose:"Platform ingress or authentication may use provider-controlled storage outside application code.",category:"external_after_action",data:"Not visible to or configurable by this application repository.",trigger:"Platform-controlled request handling, where enabled.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:true,retention:"Controlled by the platform’s applicable notice and configuration.",leavesDevice:true,userCanClear:true,clearing:"Browser controls and the platform’s privacy controls.",sourceModules:["app/chatgpt-auth.ts"],state:"provider_controlled" }),
  entry({ key:"stripe_site",name:"Stripe-hosted payment storage",technology:"third_party_site",browserKey:null,keyPattern:null,party:"third_party",provider:"Stripe",purpose:"Process a deliberate Royal Reveal payment on Stripe’s site.",category:"external_after_action",data:"Controlled by Stripe; the application does not receive card details.",trigger:"Only after the user confirms immediate delivery and chooses Unlock, while commerce is separately activated.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:false,retention:"Under Stripe’s own privacy and storage policies.",leavesDevice:true,userCanClear:true,clearing:"Stripe and browser controls; application local clearing removes only the pending return reference.",sourceModules:["app/RoyalRevealOffer.tsx"],state:"feature_gated" }),
  entry({ key:"social_sites",name:"Social-platform storage",technology:"third_party_site",browserKey:null,keyPattern:null,party:"third_party",provider:"The social platform selected by the user",purpose:"Open a share composer or receive a deliberate browser share handoff.",category:"external_after_action",data:"Controlled by the selected platform after navigation or handoff.",trigger:"Only after the user selects a social sharing action.",existsBeforeChoice:false,requiresAnalyticsConsent:false,strictlyFunctional:false,retention:"Under the selected platform’s own policies.",leavesDevice:true,userCanClear:true,clearing:"Platform and browser controls.",sourceModules:["app/ShareCentre.tsx","app/NominateThreePanel.tsx"],state:"enabled" }),
]);

export const localStorageAllowlist = Object.freeze(storageInventory.filter((item) => item.technology === "localStorage" && item.browserKey).map((item) => item.browserKey as string));
export const sessionStorageAllowlist = Object.freeze(storageInventory.filter((item) => item.technology === "sessionStorage" && item.browserKey).map((item) => item.browserKey as string));
export const sessionStoragePrefixAllowlist = Object.freeze(["wybp-nomination-v1:"] as const);

type ClearableStorage = Pick<Storage, "length" | "key" | "removeItem">;
export function clearApplicationLocalData(local: ClearableStorage, session: ClearableStorage): Readonly<{ removed: readonly string[] }> {
  const removed: string[] = [];
  for (const key of localStorageAllowlist) { try { local.removeItem(key); removed.push(`localStorage:${key}`); } catch { /* continue with the explicit allowlist */ } }
  for (const key of sessionStorageAllowlist) { try { session.removeItem(key); removed.push(`sessionStorage:${key}`); } catch { /* continue with the explicit allowlist */ } }
  const patterned: string[] = [];
  try {
    for (let index = 0; index < session.length; index += 1) {
      const key = session.key(index);
      if (key && sessionStoragePrefixAllowlist.some((prefix) => key.startsWith(prefix))) patterned.push(key);
    }
  } catch { /* unavailable storage fails closed */ }
  for (const key of patterned) { try { session.removeItem(key); removed.push(`sessionStorage:${key}`); } catch { /* continue */ } }
  return Object.freeze({ removed: Object.freeze(removed) });
}
