import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const quizEditions = sqliteTable("quiz_editions", {
  id: text("id").primaryKey(),
  editionKey: text("edition_key").notNull(),
  name: text("name").notNull(),
  region: text("region").notNull(),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  retiredAt: integer("retired_at"),
}, (table) => [
  uniqueIndex("quiz_editions_key_version_uq").on(table.editionKey, table.version),
  index("quiz_editions_status_idx").on(table.status),
  check("quiz_editions_key_ck", sql`${table.editionKey} in ('west','east','central','north','south')`),
  check("quiz_editions_status_ck", sql`${table.status} in ('active','retired')`),
  check("quiz_editions_version_ck", sql`${table.version} >= 1`),
]);

export const questions = sqliteTable("questions", {
  id: text("id").primaryKey(),
  stableId: text("stable_id").notNull(),
  version: integer("version").notNull(),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  countryScope: text("country_scope"),
  subregionScope: text("subregion_scope"),
  communityScope: text("community_scope"),
  category: text("category").notNull(),
  difficulty: text("difficulty"),
  questionKind: text("question_kind").notNull(),
  questionText: text("question_text").notNull(),
  answerOptionsJson: text("answer_options_json").notNull(),
  correctAnswerJson: text("correct_answer_json").notNull(),
  explanation: text("explanation").notNull(),
  visualStart: integer("visual_start"),
  scoringWeight: integer("scoring_weight").notNull().default(1),
  locale: text("locale").notNull().default("en"),
  publicationStatus: text("publication_status").notNull().default("draft"),
  sourceReviewStatus: text("source_review_status").notNull().default("pending"),
  sensitivityNotes: text("sensitivity_notes"),
  contentHash: text("content_hash").notNull(),
  publishedAt: integer("published_at"),
  retiredAt: integer("retired_at"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("questions_stable_version_uq").on(table.stableId, table.version),
  index("questions_playable_idx").on(table.editionId, table.publicationStatus, table.sourceReviewStatus),
  index("questions_category_idx").on(table.editionId, table.category),
  check("questions_version_ck", sql`${table.version} >= 1`),
  check("questions_weight_ck", sql`${table.scoringWeight} between 1 and 100`),
  check("questions_visual_start_ck", sql`${table.visualStart} is null or ${table.visualStart} between 0 and 999`),
  check("questions_kind_ck", sql`${table.questionKind} in ('single','multi','complete','image')`),
  check("questions_difficulty_ck", sql`${table.difficulty} is null or ${table.difficulty} in ('introductory','intermediate','advanced')`),
  check("questions_publication_ck", sql`${table.publicationStatus} in ('draft','review','published','retired','rejected')`),
  check("questions_source_review_ck", sql`${table.sourceReviewStatus} in ('pending','in_review','approved','rejected')`),
  check("questions_json_ck", sql`json_valid(${table.answerOptionsJson}) and json_type(${table.answerOptionsJson}) = 'array' and json_valid(${table.correctAnswerJson}) and json_type(${table.correctAnswerJson}) = 'array'`),
  check("questions_playable_dates_ck", sql`${table.publicationStatus} != 'published' or (${table.sourceReviewStatus} = 'approved' and ${table.publishedAt} is not null)`),
]);

export const questionSources = sqliteTable("question_sources", {
  id: text("id").primaryKey(),
  questionId: text("question_id").references(() => questions.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  organisationOrAuthor: text("organisation_or_author").notNull(),
  urlOrReference: text("url_or_reference").notNull(),
  publicationDate: text("publication_date"),
  accessDate: text("access_date").notNull(),
  sourceType: text("source_type").notNull(),
  reviewStatus: text("review_status").notNull().default("pending"),
  reviewer: text("reviewer"),
  reviewDate: text("review_date"),
  relevantClaim: text("relevant_claim"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("question_sources_question_idx").on(table.questionId, table.reviewStatus),
  uniqueIndex("question_sources_reference_uq").on(table.questionId, table.urlOrReference, table.relevantClaim),
  check("question_sources_status_ck", sql`${table.reviewStatus} in ('pending','in_review','approved','rejected')`),
  check("question_sources_type_ck", sql`${table.sourceType} in ('primary','academic','museum','heritage','book','article','oral_history','other')`),
]);

export const quizAttempts = sqliteTable("quiz_attempts", {
  id: text("id").primaryKey(),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  anonymousSubjectHash: text("anonymous_subject_hash"),
  questionSetVersion: text("question_set_version").notNull(),
  scoringVersion: text("scoring_version").notNull(),
  selectedQuestionVersionsJson: text("selected_question_versions_json").notNull(),
  status: text("status").notNull().default("in_progress"),
  idempotencyKeyHash: text("idempotency_key_hash").notNull(),
  referralCode: text("referral_code"),
  challengeCode: text("challenge_code"),
  startedAt: integer("started_at").notNull(),
  completedAt: integer("completed_at"),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("quiz_attempts_idempotency_uq").on(table.idempotencyKeyHash),
  index("quiz_attempts_subject_idx").on(table.anonymousSubjectHash, table.createdAt),
  index("quiz_attempts_expiry_idx").on(table.status, table.expiresAt),
  index("quiz_attempts_challenge_idx").on(table.challengeCode),
  check("quiz_attempts_status_ck", sql`${table.status} in ('in_progress','completed','abandoned','expired','anonymized','deleted')`),
  check("quiz_attempts_questions_json_ck", sql`json_valid(${table.selectedQuestionVersionsJson}) and json_type(${table.selectedQuestionVersionsJson}) = 'array'`),
]);

export const answers = sqliteTable("answers", {
  id: text("id").primaryKey(),
  attemptId: text("attempt_id").notNull().references(() => quizAttempts.id, { onDelete: "cascade" }),
  questionId: text("question_id").notNull().references(() => questions.id, { onDelete: "restrict" }),
  questionVersion: integer("question_version").notNull(),
  selectedOptionIdsJson: text("selected_option_ids_json").notNull(),
  isCorrect: integer("is_correct", { mode: "boolean" }).notNull(),
  scoreAwarded: integer("score_awarded").notNull(),
  answeredAt: integer("answered_at").notNull(),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("answers_attempt_question_uq").on(table.attemptId, table.questionId),
  index("answers_attempt_idx").on(table.attemptId, table.answeredAt),
  check("answers_question_version_ck", sql`${table.questionVersion} >= 1`),
  check("answers_score_ck", sql`${table.scoreAwarded} between 0 and 100`),
  check("answers_options_json_ck", sql`json_valid(${table.selectedOptionIdsJson}) and json_type(${table.selectedOptionIdsJson}) = 'array'`),
]);

export const results = sqliteTable("results", {
  id: text("id").primaryKey(),
  publicSlug: text("public_slug").notNull(),
  attemptId: text("attempt_id").notNull().references(() => quizAttempts.id, { onDelete: "restrict" }),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  score: integer("score").notNull(),
  total: integer("total").notNull(),
  tier: integer("tier").notNull(),
  scoringVersion: text("scoring_version").notNull(),
  questionSetVersion: text("question_set_version").notNull(),
  scoringSnapshotJson: text("scoring_snapshot_json").notNull(),
  safeAvatarId: text("safe_avatar_id"),
  reviewedDisplayName: text("reviewed_display_name"),
  safeguardVersion: text("safeguard_version").notNull(),
  visibility: text("visibility").notNull().default("private"),
  state: text("state").notNull().default("active"),
  expiresAt: integer("expires_at"),
  revokedAt: integer("revoked_at"),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("results_public_slug_uq").on(table.publicSlug),
  uniqueIndex("results_attempt_uq").on(table.attemptId),
  index("results_public_lookup_idx").on(table.publicSlug, table.state, table.expiresAt),
  index("results_edition_created_idx").on(table.editionId, table.createdAt),
  check("results_score_ck", sql`${table.total} between 1 and 100 and ${table.score} between 0 and ${table.total}`),
  check("results_tier_ck", sql`${table.tier} between 0 and 3`),
  check("results_visibility_ck", sql`${table.visibility} in ('private','public')`),
  check("results_state_ck", sql`${table.state} in ('active','expired','revoked','anonymized','deleted')`),
  check("results_snapshot_json_ck", sql`json_valid(${table.scoringSnapshotJson}) and json_type(${table.scoringSnapshotJson}) = 'object'`),
]);

export const challenges = sqliteTable("challenges", {
  id: text("id").primaryKey(),
  publicCode: text("public_code").notNull(),
  inviterResultId: text("inviter_result_id").references(() => results.id, { onDelete: "set null" }),
  creationIdempotencyKeyHash: text("creation_idempotency_key_hash"),
  revocationTokenHash: text("revocation_token_hash"),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  verifiedScoreToBeat: integer("verified_score_to_beat").notNull(),
  total: integer("total").notNull(),
  scoringVersion: text("scoring_version").notNull(),
  safeInviterAvatarId: text("safe_inviter_avatar_id"),
  reviewedInviterName: text("reviewed_inviter_name"),
  state: text("state").notNull().default("active"),
  useLimit: integer("use_limit"),
  useCount: integer("use_count").notNull().default(0),
  expiresAt: integer("expires_at").notNull(),
  revokedAt: integer("revoked_at"),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("challenges_public_code_uq").on(table.publicCode),
  uniqueIndex("challenges_creation_idempotency_hash_uq")
    .on(table.creationIdempotencyKeyHash)
    .where(sql`${table.creationIdempotencyKeyHash} is not null`),
  uniqueIndex("challenges_revocation_token_hash_uq")
    .on(table.revocationTokenHash)
    .where(sql`${table.revocationTokenHash} is not null`),
  index("challenges_lookup_idx").on(table.publicCode, table.state, table.expiresAt),
  index("challenges_inviter_idx").on(table.inviterResultId, table.createdAt),
  check("challenges_score_ck", sql`${table.total} between 1 and 100 and ${table.verifiedScoreToBeat} between 0 and ${table.total}`),
  check("challenges_state_ck", sql`${table.state} in ('active','expired','revoked','unavailable','anonymized','deleted')`),
  check("challenges_use_ck", sql`${table.useCount} >= 0 and (${table.useLimit} is null or (${table.useLimit} > 0 and ${table.useCount} <= ${table.useLimit}))`),
]);

export const challengeAttempts = sqliteTable("challenge_attempts", {
  id: text("id").primaryKey(),
  challengeId: text("challenge_id").notNull().references(() => challenges.id, { onDelete: "cascade" }),
  recipientAttemptId: text("recipient_attempt_id").notNull().references(() => quizAttempts.id, { onDelete: "restrict" }),
  recipientSubjectHash: text("recipient_subject_hash"),
  officialResultId: text("official_result_id").references(() => results.id, { onDelete: "set null" }),
  isOfficialComparison: integer("is_official_comparison", { mode: "boolean" }).notNull().default(false),
  idempotencyKeyHash: text("idempotency_key_hash").notNull(),
  scoringVersion: text("scoring_version").notNull(),
  outcome: text("outcome").notNull().default("pending"),
  state: text("state").notNull().default("accepted"),
  acceptedAt: integer("accepted_at").notNull(),
  completedAt: integer("completed_at"),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("challenge_attempts_challenge_attempt_uq").on(table.challengeId, table.recipientAttemptId),
  uniqueIndex("challenge_attempts_idempotency_uq").on(table.idempotencyKeyHash),
  uniqueIndex("challenge_attempts_official_recipient_uq")
    .on(table.challengeId, table.recipientSubjectHash)
    .where(sql`${table.isOfficialComparison} = 1 and ${table.recipientSubjectHash} is not null`),
  uniqueIndex("challenge_attempts_official_result_uq")
    .on(table.officialResultId)
    .where(sql`${table.officialResultId} is not null`),
  index("challenge_attempts_challenge_idx").on(table.challengeId, table.state),
  check("challenge_attempts_outcome_ck", sql`${table.outcome} in ('pending','beat','tied','not_beat','incompatible','unavailable')`),
  check("challenge_attempts_state_ck", sql`${table.state} in ('accepted','completed','expired','anonymized','deleted')`),
  check("challenge_attempts_official_marker_ck", sql`${table.isOfficialComparison} in (0,1)`),
]);

export const referralEvents = sqliteTable("referral_events", {
  id: text("id").primaryKey(),
  referralCode: text("referral_code").notNull(),
  challengeId: text("challenge_id").references(() => challenges.id, { onDelete: "set null" }),
  attemptId: text("attempt_id").references(() => quizAttempts.id, { onDelete: "set null" }),
  eventType: text("event_type").notNull(),
  source: text("source").notNull().default("unknown"),
  anonymousSubjectHash: text("anonymous_subject_hash"),
  occurredAt: integer("occurred_at").notNull(),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("referral_events_code_time_idx").on(table.referralCode, table.occurredAt),
  index("referral_events_retention_idx").on(table.expiresAt, table.deletedAt),
  check("referral_events_type_ck", sql`${table.eventType} in ('link_created','referred_visit_received','challenge_accepted','quiz_started','quiz_completed')`),
]);

export const shareEvents = sqliteTable("share_events", {
  id: text("id").primaryKey(),
  resultId: text("result_id").references(() => results.id, { onDelete: "set null" }),
  challengeId: text("challenge_id").references(() => challenges.id, { onDelete: "set null" }),
  eventType: text("event_type").notNull(),
  channel: text("channel").notNull(),
  anonymousSubjectHash: text("anonymous_subject_hash"),
  occurredAt: integer("occurred_at").notNull(),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("share_events_result_time_idx").on(table.resultId, table.occurredAt),
  index("share_events_retention_idx").on(table.expiresAt, table.deletedAt),
  check("share_events_type_ck", sql`${table.eventType} in ('share_interface_selected','share_handoff_attempted','link_copied')`),
  check("share_events_channel_ck", sql`${table.channel} in ('native','whatsapp','facebook','instagram','tiktok','clipboard','download','other')`),
]);

export const dailyChallenges = sqliteTable("daily_challenges", {
  id: text("id").primaryKey(),
  challengeDate: text("challenge_date").notNull(),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  questionSetVersion: text("question_set_version").notNull(),
  deterministicSeedHash: text("deterministic_seed_hash").notNull(),
  selectedQuestionVersionsJson: text("selected_question_versions_json").notNull(),
  state: text("state").notNull().default("planned"),
  expiresAt: integer("expires_at").notNull(),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("daily_challenges_date_edition_uq").on(table.challengeDate, table.editionId),
  index("daily_challenges_state_date_idx").on(table.state, table.challengeDate),
  check("daily_challenges_state_ck", sql`${table.state} in ('planned','active','expired','cancelled')`),
  check("daily_challenges_questions_json_ck", sql`json_valid(${table.selectedQuestionVersionsJson}) and json_type(${table.selectedQuestionVersionsJson}) = 'array'`),
]);

export const streaks = sqliteTable("streaks", {
  id: text("id").primaryKey(),
  anonymousSubjectHash: text("anonymous_subject_hash").notNull(),
  streakType: text("streak_type").notNull(),
  currentCount: integer("current_count").notNull().default(0),
  longestCount: integer("longest_count").notNull().default(0),
  lastQualifyingDate: text("last_qualifying_date"),
  ruleVersion: text("rule_version").notNull(),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("streaks_subject_type_uq").on(table.anonymousSubjectHash, table.streakType),
  index("streaks_expiry_idx").on(table.expiresAt, table.deletedAt),
  check("streaks_counts_ck", sql`${table.currentCount} >= 0 and ${table.longestCount} >= ${table.currentCount}`),
]);

export const masterySeals = sqliteTable("mastery_seals", {
  id: text("id").primaryKey(),
  anonymousSubjectHash: text("anonymous_subject_hash").notNull(),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  resultId: text("result_id").notNull().references(() => results.id, { onDelete: "restrict" }),
  ruleVersion: text("rule_version").notNull(),
  earnedAt: integer("earned_at").notNull(),
  state: text("state").notNull().default("active"),
  revokedAt: integer("revoked_at"),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("mastery_seals_subject_edition_rule_uq").on(table.anonymousSubjectHash, table.editionId, table.ruleVersion),
  index("mastery_seals_subject_idx").on(table.anonymousSubjectHash, table.state),
  check("mastery_seals_state_ck", sql`${table.state} in ('active','revoked','anonymized','deleted')`),
]);

export const parties = sqliteTable("parties", {
  id: text("id").primaryKey(),
  publicCode: text("public_code").notNull(),
  hostControlTokenHash: text("host_control_token_hash").notNull(),
  editionId: text("edition_id").notNull().references(() => quizEditions.id, { onDelete: "restrict" }),
  maxPlayers: integer("max_players").notNull().default(20),
  leaderboardRuleVersion: text("leaderboard_rule_version").notNull(),
  state: text("state").notNull().default("open"),
  startsAt: integer("starts_at"),
  closedAt: integer("closed_at"),
  expiresAt: integer("expires_at").notNull(),
  revokedAt: integer("revoked_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("parties_public_code_uq").on(table.publicCode),
  index("parties_lookup_idx").on(table.publicCode, table.state, table.expiresAt),
  check("parties_capacity_ck", sql`${table.maxPlayers} between 2 and 20`),
  check("parties_state_ck", sql`${table.state} in ('open','started','closed','expired','revoked','deleted')`),
]);

export const partyPlayers = sqliteTable("party_players", {
  id: text("id").primaryKey(),
  partyId: text("party_id").notNull().references(() => parties.id, { onDelete: "cascade" }),
  playerPublicId: text("player_public_id").notNull(),
  safeAvatarId: text("safe_avatar_id").notNull(),
  reviewedDisplayName: text("reviewed_display_name"),
  resultId: text("result_id").references(() => results.id, { onDelete: "set null" }),
  score: integer("score"),
  rankTieBreaker: text("rank_tie_breaker").notNull(),
  state: text("state").notNull().default("joined"),
  joinedAt: integer("joined_at").notNull(),
  completedAt: integer("completed_at"),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("party_players_party_public_uq").on(table.partyId, table.playerPublicId),
  uniqueIndex("party_players_party_result_uq").on(table.partyId, table.resultId),
  index("party_players_leaderboard_idx").on(table.partyId, table.score, table.completedAt, table.rankTieBreaker),
  check("party_players_score_ck", sql`${table.score} is null or ${table.score} between 0 and 100`),
  check("party_players_state_ck", sql`${table.state} in ('joined','playing','completed','left','anonymized','deleted')`),
]);

export const mediaAssets = sqliteTable("media_assets", {
  id: text("id").primaryKey(),
  objectKey: text("object_key").notNull(),
  mediaType: text("media_type").notNull(),
  ownerType: text("owner_type").notNull(),
  ownerId: text("owner_id").notNull(),
  resultId: text("result_id").references(() => results.id, { onDelete: "set null" }),
  editionId: text("edition_id").references(() => quizEditions.id, { onDelete: "restrict" }),
  width: integer("width").notNull(),
  height: integer("height").notNull(),
  mimeType: text("mime_type").notNull(),
  byteSize: integer("byte_size").notNull(),
  contentHash: text("content_hash").notNull(),
  generationVersion: text("generation_version").notNull(),
  privacyClassification: text("privacy_classification").notNull(),
  state: text("state").notNull().default("pending"),
  expiresAt: integer("expires_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("media_assets_object_key_uq").on(table.objectKey),
  index("media_assets_owner_idx").on(table.ownerType, table.ownerId, table.state),
  index("media_assets_result_idx").on(table.resultId, table.state),
  index("media_assets_expiry_idx").on(table.expiresAt, table.deletedAt),
  check("media_assets_type_ck", sql`${table.mediaType} in ('result_portrait','open_graph','story_image','story_video','party_card')`),
  check("media_assets_mime_ck", sql`${table.mimeType} in ('image/png','image/webp','video/mp4','video/webm')`),
  check("media_assets_dimensions_ck", sql`${table.width} between 1 and 8192 and ${table.height} between 1 and 8192 and ${table.byteSize} between 1 and 52428800`),
  check("media_assets_privacy_ck", sql`${table.privacyClassification} in ('private','safe_public','owner_only')`),
  check("media_assets_state_ck", sql`${table.state} in ('pending','ready','expired','revoked','deleted')`),
]);

export const consentPreferences = sqliteTable("consent_preferences", {
  id: text("id").primaryKey(),
  anonymousSubjectHash: text("anonymous_subject_hash").notNull(),
  noticeVersion: text("notice_version").notNull(),
  categoryVersion: text("category_version").notNull(),
  strictlyFunctional: integer("strictly_functional", { mode: "boolean" }).notNull().default(true),
  firstPartyStatistical: integer("first_party_statistical", { mode: "boolean" }).notNull().default(false),
  marketing: integer("marketing", { mode: "boolean" }).notNull().default(false),
  decidedAt: integer("decided_at").notNull(),
  withdrawnAt: integer("withdrawn_at"),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("consent_preferences_subject_notice_uq").on(table.anonymousSubjectHash, table.noticeVersion),
  index("consent_preferences_expiry_idx").on(table.expiresAt, table.deletedAt),
  check("consent_preferences_functional_ck", sql`${table.strictlyFunctional} = 1`),
]);

export const analyticsEvents = sqliteTable("analytics_events", {
  id: text("id").primaryKey(),
  eventName: text("event_name").notNull(),
  propertiesJson: text("properties_json").notNull().default("{}"),
  anonymousSubjectHash: text("anonymous_subject_hash"),
  consentNoticeVersion: text("consent_notice_version"),
  botClassification: text("bot_classification").notNull().default("unknown"),
  occurredAt: integer("occurred_at").notNull(),
  expiresAt: integer("expires_at").notNull(),
  anonymizedAt: integer("anonymized_at"),
  deletedAt: integer("deleted_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  index("analytics_events_name_time_idx").on(table.eventName, table.occurredAt),
  index("analytics_events_retention_idx").on(table.expiresAt, table.deletedAt),
  check("analytics_events_name_ck", sql`${table.eventName} in ('entry_viewed','region_selected','avatar_selected','quiz_started','question_answered','quiz_completed','result_viewed','share_interface_selected','share_handoff_attempted','link_copied','referred_visit_received','challenge_accepted')`),
  check("analytics_events_bot_ck", sql`${table.botClassification} in ('human','bot','crawler','unknown')`),
  check("analytics_events_json_ck", sql`json_valid(${table.propertiesJson}) and json_type(${table.propertiesJson}) = 'object' and length(${table.propertiesJson}) <= 2048`),
]);

export const featureFlagOverrides = sqliteTable("feature_flag_overrides", {
  id: text("id").primaryKey(),
  flagName: text("flag_name").notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull(),
  scopeType: text("scope_type").notNull(),
  scopeValueHash: text("scope_value_hash"),
  reason: text("reason").notNull(),
  createdByOwnerId: text("created_by_owner_id").notNull(),
  expiresAt: integer("expires_at").notNull(),
  revokedAt: integer("revoked_at"),
  version: integer("version").notNull().default(1),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (table) => [
  uniqueIndex("feature_flag_overrides_scope_uq").on(table.flagName, table.scopeType, table.scopeValueHash, table.expiresAt),
  index("feature_flag_overrides_active_idx").on(table.flagName, table.scopeType, table.expiresAt, table.revokedAt),
  check("feature_flag_overrides_name_ck", sql`${table.flagName} in ('fast_entry','challenges','dynamic_results','story_video','first_party_analytics','daily_challenge','streaks','groom_mode','couples_mode','party_mode','premium_preview','commerce')`),
  check("feature_flag_overrides_scope_ck", sql`${table.scopeType} in ('global','edition','anonymous_subject','owner_preview')`),
  check("feature_flag_overrides_reason_ck", sql`length(${table.reason}) between 3 and 500`),
]);

export const durableTableNames = [
  "quiz_editions", "questions", "question_sources", "quiz_attempts", "answers", "results",
  "challenges", "challenge_attempts", "referral_events", "share_events", "daily_challenges",
  "streaks", "mastery_seals", "parties", "party_players", "media_assets",
  "consent_preferences", "analytics_events", "feature_flag_overrides",
] as const;
