import assert from "node:assert/strict";
import test from "node:test";
import {defaultFeatureFlags,resolveFeatureFlags} from "../../app/featureFlags.ts";
import {validateCommerceConfiguration,validatePaymentLinkUrl,validateStartOrderRequest,verifyStripeWebhook,derivePaymentIntentHash} from "../../db/commerceContracts.ts";
import {config,now,rawEvent,sign,setup,request,checkout,adverse} from "../helpers/cowrieCommerce.mjs";
import {cowrieProducts,COWRIE_DELIVERY_NOTICE_VERSION} from "../../db/cowrieProducts.ts";
import {safeCommerceRequest,readCommerceJson,readLimitedCommerceBody} from "../../app/commerceHttp.ts";
import {COWRIE_PENDING_ORDER_KEY,readPendingCowrieOrder,savePendingCowrieOrder,createCowriePurchase,readCowriePurchaseStatus} from "../../app/cowrieCommerceClient.ts";

test("exact three one-off controlled products, all activation flags false, query/storage shapes cannot activate",()=>{assert.deepEqual(Object.keys(cowrieProducts),["cowrie_5_v1","cowrie_15_v1","cowrie_40_v1"]);assert.deepEqual(Object.values(cowrieProducts).map(p=>[p.quantity,p.amountMinor]),[[5,199],[15,499],[40,999]]);for(const flag of ["commerce","cowrie_economy","random_quick_play","first_party_analytics","daily_challenge","streaks","owner_dashboard"])assert.equal(defaultFeatureFlags[flag],false);assert.deepEqual(resolveFeatureFlags({commerce:"true",cowrie_economy:"true",random_quick_play:"true",search:"?commerce=1"}),defaultFeatureFlags);});
test("configuration rejects arbitrary URLs, ports, fragments, browser prices, quantity, currency and link/product mismatches",()=>{validateCommerceConfiguration(config);for(const url of ["http://buy.stripe.com/test","https://buy.stripe.com:444/test","https://buy.stripe.com.evil.example/test","https://u:p@buy.stripe.com/test","https://buy.stripe.com/test#x","https://buy.stripe.com/test?x=1","//buy.stripe.com/test"])assert.throws(()=>validatePaymentLinkUrl(url),/payment_link/);for(const mutation of [{expectedQuantity:6},{expectedAmountMinor:200},{expectedCurrency:"USD"},{expectedProductKey:"cowrie_40_v1"},{expectedLivemode:true},{expectedPaymentLinkId:config.expectedPaymentLinkId}])assert.throws(()=>validateCommerceConfiguration({...config,cowrieBundles:{...config.cowrieBundles,cowrie_5_v1:{...config.cowrieBundles.cowrie_5_v1,...mutation}}}),/configuration/);});
test("strict consent, notice, field allowlist and controlled targets cannot be supplied from checkout/browser state",()=>{const c={created:{wallet:{walletReference:`cw_${"1".repeat(32)}`}}};const valid=request(c);assert.equal(validateStartOrderRequest(valid).consentNoticeVersion,COWRIE_DELIVERY_NOTICE_VERSION);for(const mutation of [{immediateDeliveryConsent:false},{consentNoticeVersion:"other"},{quantity:999},{price:0},{currency:"USD"},{balance:99},{walletOwnerHash:"f".repeat(64)},{stripePaymentIntentId:"pi_browser"},{state:"fulfilled"},{resultSlug:"a".repeat(48)}])assert.throws(()=>validateStartOrderRequest({...valid,...mutation}),/(consent|field)/);});
test("same-origin POST, CSRF and Fetch Metadata enforced; body size checked while streaming",async()=>{const url="https://brideprice.classesforculture.com/commerce/orders";const headers={origin:new URL(url).origin,"sec-fetch-site":"same-origin","sec-fetch-mode":"cors","content-type":"application/json"};assert.equal(safeCommerceRequest(new Request(url,{method:"POST",headers})),true);for(const variation of [{origin:"https://evil.example"},{"sec-fetch-site":"cross-site"},{"sec-fetch-site":"same-site"},{"sec-fetch-mode":"navigate"}])assert.equal(safeCommerceRequest(new Request(url,{method:"POST",headers:{...headers,...variation}})),false);assert.equal(safeCommerceRequest(new Request(url,{headers})),false);assert.equal(safeCommerceRequest(new Request("https://evil.example/commerce/orders",{method:"POST",headers:{...headers,origin:"https://evil.example"}})),false);await assert.rejects(readCommerceJson(new Request(url,{method:"POST",headers,body:"x".repeat(16385)})),/size/);let cancelled=false;const body=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(65537));},cancel(){cancelled=true;}});await assert.rejects(readLimitedCommerceBody(new Request(url,{method:"POST",body,duplex:"half"}),65536),/size/);assert.equal(cancelled,true);});
test("signature-first verification stores no facts for invalid, expired, oversized, wrong-live, unknown-type, malformed events or excessive refunds",async()=>{const c=await setup();try{const order=await c.service.startOrder(request(c));const good=rawEvent("checkout.session.completed",checkout(order));const invalid=[{rawBody:good,signatureHeader:"t=1,v1="+"0".repeat(64)},{rawBody:good,signatureHeader:sign(good,Math.floor(now/1000)-301)},{rawBody:good+" ",signatureHeader:sign(good)},{rawBody:"x".repeat(65537),signatureHeader:sign("x".repeat(65537))}];for(const item of invalid)await assert.rejects(verifyStripeWebhook({...item,config,now}),/signature/);for(const raw of [rawEvent("checkout.session.completed",checkout(order),{livemode:true}),rawEvent("customer.created",{}),rawEvent("charge.refunded",adverse(undefined,199,200)),rawEvent("charge.refunded",{...adverse(),payment_intent:"pi_!bad"}),"{bad-json",rawEvent("checkout.session.async_payment_succeeded",checkout(order,undefined,undefined,"unpaid"))])await assert.rejects(verifyStripeWebhook({rawBody:raw,signatureHeader:sign(raw),config,now}),/stripe_/);await assert.rejects(c.repository.processVerifiedWebhook({stripeEventId:"evt_forged",paymentIntentHash:"a".repeat(64)},now),/unverified/);assert.equal(c.database.prepare("SELECT COUNT(*) n FROM stripe_webhook_events").get().n,0);const event=await verifyStripeWebhook({rawBody:good,signatureHeader:`t=${Math.floor(now/1000)},v1=${"0".repeat(64)},${sign(good).split(",")[1]}`,config,now});await c.service.webhook(event);const stored=c.database.prepare("SELECT * FROM stripe_webhook_events").get();assert.equal(stored.payment_intent_hash,await derivePaymentIntentHash("pi_local_D_primary"));assert.doesNotMatch(JSON.stringify(stored),/(pi_local|ch_local|customer|email|card|data.*object)/);assert.doesNotMatch(JSON.stringify(event),/pi_local/);}finally{c.database.close();}});
test("delayed checkout without a Payment Intent has nullable reconciliation facts and cannot credit",async()=>{const c=await setup();try{const order=await c.service.startOrder(request(c));const raw=rawEvent("checkout.session.completed",{...checkout(order,undefined,undefined,"unpaid"),payment_intent:null});const event=await verifyStripeWebhook({rawBody:raw,signatureHeader:sign(raw),config,now});assert.equal(event.paymentIntentHash,null);await c.service.webhook(event);assert.equal(c.database.prepare("SELECT purchased_balance FROM cowrie_wallets").get().purchased_balance,0);}finally{c.database.close();}});
test("tab-local state stores only an opaque reference, rejects query/JSON/Stripe IDs and no return-shaped status can fulfil",async()=>{const storage=new Map();const adapter={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)};const reference=`rr_${"1".repeat(32)}`;savePendingCowrieOrder(adapter,reference);assert.equal(storage.get(COWRIE_PENDING_ORDER_KEY),reference);assert.equal(readPendingCowrieOrder(adapter),reference);for(const value of ["pi_browser",`${reference}?paid=1`,JSON.stringify({reference,paid:true}),"cs_browser"]){storage.set(COWRIE_PENDING_ORDER_KEY,value);assert.equal(readPendingCowrieOrder(adapter),null);}const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({success:true,paid:true,quantity:999,balance:999,session_id:"cs_browser"});try{await assert.rejects(readCowriePurchaseStatus(reference,"a".repeat(32)),/unavailable/);await assert.rejects(createCowriePurchase({productKey:"cowrie_5_v1",walletReference:`cw_${"a".repeat(32)}`,anonymousSessionCredential:"a".repeat(32),idempotencyKey:"b".repeat(32),consent:false}),/consent/);}finally{globalThis.fetch=original;}});
