import assert from "node:assert/strict";
import test from "node:test";
import { PRODUCT_SAFEGUARD } from "../../app/productSafeguards.ts";
import { InMemoryGeneratedMediaStore, InMemoryResultPreviewRepository, ResultMediaService } from "../../db/resultMedia.ts";

const now = Date.UTC(2026, 7, 24, 12); const slug = "8".repeat(48);
const result = Object.freeze({ resultSlug: slug, edition: "west", score: 12, total: 12, tier: 3, safeAvatarId: "adjoa", scoringVersion: "binary-exact-set-v1", safeguard: PRODUCT_SAFEGUARD, createdAt: now, expiresAt: now + 1000, displayName: "A challenger" });

test("media preparation is idempotent and public lookup cannot enumerate object keys", async () => {
  const repository = new InMemoryResultPreviewRepository(); const objects = new InMemoryGeneratedMediaStore(); const media = new ResultMediaService(repository, objects);
  const first = await media.prepare("result_internal", result); const second = await media.prepare("result_internal", result);
  assert.deepEqual(second, first); assert.equal(repository.writeCount.save, 1);
  assert.ok(await media.get(slug, first.contentHash));
  assert.equal(await media.get("../private", first.contentHash), null);
  assert.equal(await media.get(slug, "f".repeat(64)), null);
  assert.equal(await media.get(slug, first.objectKey), null);
});

test("unpublication revokes metadata and deletes generated bytes", async () => {
  const repository = new InMemoryResultPreviewRepository(); const media = new ResultMediaService(repository, new InMemoryGeneratedMediaStore());
  const stored = await media.prepare("result_internal", result); await media.revoke("result_internal", slug);
  assert.equal(await media.get(slug, stored.contentHash), null); assert.equal(repository.writeCount.revoke, 1);
});

test("generated media fails closed when metadata or object storage is unavailable", async () => {
  for (const service of [new ResultMediaService(new InMemoryResultPreviewRepository(false), new InMemoryGeneratedMediaStore()), new ResultMediaService(new InMemoryResultPreviewRepository(), new InMemoryGeneratedMediaStore(false))]) {
    assert.equal(service.storageAvailable, false); await assert.rejects(service.prepare("result_internal", result), /storage_unavailable/); assert.equal(await service.get(slug, "a".repeat(64)), null);
  }
});
