import type { Metadata } from "next";
import { LegalPage, draftRobots } from "../../legalPage.tsx";
import { createPublicAppUrl } from "../../publicAppOrigin.ts";
import { storageInventory } from "../../storageInventory.ts";

export const metadata:Metadata={title:"Cookie and Local Storage Notice | What’s Your Bride Price?",description:"Storage and browser-access inventory for What’s Your Bride Price?.",alternates:{canonical:createPublicAppUrl("/privacy/storage")},robots:draftRobots};
export default function StoragePage(){return <LegalPage kicker="Storage inventory" title="Cookie and Local Storage Notice">
  <p>Cookies, local storage, session storage, in-memory files, object URLs and device APIs are different technologies. This application does not label them all as cookies.</p><p>Automated repository checks find no application-owned cookie writes, IndexedDB, Cache Storage or service-worker registration. Platform or third-party sites may control their own storage outside this application. No advertising or marketing tracking is installed.</p>
  <h2>Make and change choices</h2><p>The persistent Privacy choices button explains required functionality and optional first-party analytics. Allow and Do not allow are equally available. Optional analytics remains off until Allow, and withdrawal removes its browser credential immediately without affecting the quiz.</p>
  <h2>Canonical inventory</h2><p>This list is generated from the same machine-readable inventory used by the product clear-data allowlist and tests. A JSON representation is available at <a href="/privacy/storage/inventory">/privacy/storage/inventory</a>.</p>
  {storageInventory.map((item)=><section className="storage-card" key={item.key} data-storage-key={item.key}><h3>{item.name}</h3><dl><dt>Technology</dt><dd>{item.technology.replaceAll("_"," ")}</dd><dt>Key</dt><dd>{item.browserKey||item.keyPattern||"None"}</dd><dt>Provider</dt><dd>{item.provider} ({item.party.replaceAll("_"," ")})</dd><dt>Purpose</dt><dd>{item.purpose}</dd><dt>Category</dt><dd>{item.category.replaceAll("_"," ")}</dd><dt>Data</dt><dd>{item.data}</dd><dt>Trigger</dt><dd>{item.trigger}</dd><dt>Before choice</dt><dd>{item.existsBeforeChoice?"Yes":"No"}</dd><dt>Analytics consent</dt><dd>{item.requiresAnalyticsConsent?"Required":"Not required"}</dd><dt>Retention</dt><dd>{item.retention}</dd><dt>Leaves device</dt><dd>{item.leavesDevice?"May leave after the stated action":"No"}</dd><dt>Clear</dt><dd>{item.clearing}</dd><dt>State</dt><dd>{item.state.replaceAll("_"," ")}</dd></dl></section>)}
  <h2>Browser and third-party controls</h2><p>Browser settings can remove site data or block storage, although disabling required functional storage may prevent recovery, ownership-dependent controls or payment return confirmation that the user deliberately requested. Stripe and social sites apply their own notices after deliberate navigation. Clear my local data never uses a broad origin-wide clear and cannot remove unrelated keys or downloaded files.</p>
 </LegalPage>}
