import Link from "next/link";
import type { Metadata } from "next";
import { createPublicAppUrl } from "../publicAppOrigin";
import { PRODUCT_SAFEGUARD, SCORING_PRINCIPLES } from "../productSafeguards";
import { PHOTO_INFORMATION, NAME_INFORMATION, RECOVERY_INFORMATION, SHARE_INFORMATION } from "../playerInformation";

export const metadata: Metadata = { title: "Game FAQ | What’s Your Bride Price?", alternates: { canonical: createPublicAppUrl("/faq") } };
export default function FAQPage() {
  return <main className="faq-shell"><header><p>Your next adventure starts here</p><h1>Game FAQ</h1><p>{PRODUCT_SAFEGUARD}</p></header>
    <nav aria-label="FAQ topics"><a href="#scoring">The game & scoring</a><a href="#photos">Photos</a><a href="#names">Names</a><a href="#recovery">Recovery</a><a href="#sharing">Sharing</a><a href="#daily">Daily play</a><a href="#purchases">Purchases</a><a href="#privacy">Privacy</a></nav>
    <section id="scoring"><h2>What’s the adventure?</h2><p>Choose a region, tackle twelve questions and discover your culture score. Every answer opens a new explanation. Quick Play draws a fresh set when its regional catalogue is ready; the classic edition has a fixed set.</p><h3>How does scoring work?</h3><ul>{SCORING_PRINCIPLES.map(text => <li key={text}>{text}</li>)}</ul><p>Africa’s cultures are diverse: a short quiz is a starting point for discovery. Question sources and cultural-reporting guidance are in About the game. Machine-evidence verification does not imply human cultural approval.</p><p>The soundtrack is an original abstract game score, not a traditional recording. The game is not directed to children under 13 in the UK.</p></section>
    <section id="photos"><h2>Can I use my own photo?</h2><p>{PHOTO_INFORMATION}</p><p>Choose an avatar whenever you prefer. A downloaded or externally shared file remains outside the game’s control.</p></section>
    <section id="names"><h2>What should we call you?</h2><p>{NAME_INFORMATION}</p><p>A name or pseudonym is optional during ordinary play. Challenge creation shows its public-name disclosure before you prepare the invitation.</p></section>
    <section id="recovery"><h2>Can I pick up where I left off?</h2><p>{RECOVERY_INFORMATION}</p><p>Expired or unavailable attempts cannot be restored. Your best scores are stored separately on this device. Private photos must be chosen again after refresh.</p></section>
    <section id="sharing"><h2>Pass the culture spark on</h2><p>{SHARE_INFORMATION}</p><p>Publishing a result is a separate choice: anyone with its public link can view it while active. Results expire 90 days after quiz completion; publishing does not extend that time. Public results exclude your entered name and private photo. You can unpublish with valid ownership proof, but outside copies and platform caches may remain.</p><p>Preparing personalised nominations creates one public challenge for all three slots. Its reviewed inviter name is visible to anyone with the link. A challenge lasts up to 30 days, never beyond its source result, and revocation or its use limit may end it sooner. Regional invitations contain no verified score or inviter identity.</p></section>
    <section id="daily"><h2>A daily adventure</h2><p>When Daily Challenges are enabled, each region shares one set per UTC day. Your first confirmed completion is official; practice does not replace it or extend a streak. When streaks are enabled, only an official completion resets their 180-day retention. A missed UTC day resets the active streak, while the best remains until expiry. Expiry or clearing makes the record unavailable immediately.</p><p>Daily play and streaks are separate optional features. See <Link href="/privacy/retention">retention information</Link> for deletion rules.</p></section>
    <section id="purchases"><h2>Cowries & Royal Reveal</h2><p>When Cowrie play access is enabled, your first two random Quick Plays are free; each additional game costs 1 Cowrie. Daily and incoming challenges stay free. One-off bundles are 5 Cowries for £1.99, 15 for £4.99 and 40 for £9.99. Purchased Cowries do not expire; bonuses may expire after 180 days. They have no cash value and cannot be transferred, resold or withdrawn.</p><p>Royal Reveal is a separate £1.99 one-off purchase for one result’s premium media pack. It does not buy Cowries or improve your score. Future regeneration is available only while the result remains active, no later than 90 days after completion; downloaded files remain yours to keep on your device.</p><p>Where purchases are enabled, checkout shows the exact contents, price, immediate digital-delivery consent and draft terms. Access follows verified payment, never a return-page redirect alone. Verified refunds and disputes follow separate settlement rules; partial refunds or consumed balances require review. Payment and legal activation remain separately gated.</p></section>
    <section id="privacy"><h2>Your choices, your adventure</h2><p>Analytics is optional and never required to play. Where enabled, it starts only after you allow it; you can withdraw in Privacy choices. It does not collect names, photos, answers or cross-site advertising identifiers. Raw events expire within 30 days.</p><p>Clearing local data removes this app’s saved recovery and preferences and releases its in-memory personal media. It cannot delete downloaded files, public links, orders or external copies; server-held actions need their own ownership checks.</p><p><Link href="/privacy">Privacy notice</Link> · <Link href="/privacy/storage">Browser storage</Link> · <Link href="/privacy/retention">Retention</Link> · <Link href="/terms">Terms</Link>. Legal content remains draft pending the documented approvals.</p></section>
    <Link href="/">Return to the game</Link>
  </main>;
}
